### ISSUE TITLE
Can't I use overwrite of Mixin?

### ISSUE THREAD

**Issue by tomocrafter** [BiscuitDevelopment/SkyblockAddons#109]
I'm trying to add this feature as pull request. so I need to overwrite renderTooltips method on GuiScreen class. 
Is there any way to use Overwrite annotation on skyblockaddons?

> Without changing the scale of GUI, I made a Mod that makes smaller scale of tooltips like enchantments only for items sold at auction!
> ![image](https://user-images.githubusercontent.com/10905364/64941649-34951d80-d8a2-11e9-889e-9a5f6107cea7.png)
> 🔗 https://twitter.com/GamingTomo/status/1166270677285888001

**Comment by biscuut** [comment]
yep messaged on discord

**Comment by ILikePlayingGames** [comment]
@biscuut has this issue been resolved?

**Comment by ILikePlayingGames** [comment]
I haven't received a reply so I assume this issue was resolved.
