### ISSUE TITLE
Subtitle size problem (in french language)

### ISSUE THREAD

**Issue by SRThibaultP** [BiscuitDevelopment/SkyblockAddons#140]
![image](https://user-images.githubusercontent.com/42326001/65836129-4d182580-e2ef-11e9-903b-07a7721a512c.png)

It's happen in all Minecraft GUI Scale

**Comment by biscuut** [comment]
thank you

**Comment by ViralTaco** [comment]
Just use English.

**Comment by SRThibaultP** [comment]
> Just use English.

I'm translating from English to French, so no. And what the meaning of this comment? Forbidden people to use others language? It's so stupid...

**Comment by ILikePlayingGames** [comment]
We fixed this in commit 33e09d9 by having 2 lines for the text instead of 1.

**Comment by ViralTaco** [comment]
> > Just use English.
> 
> I'm translating from English to French, so no. And what the meaning of this comment? Forbidden people to use others language? It's so stupid...

"melon/pasteque" Pick one. It's a lazy translation.
