### ISSUE TITLE
Sugar cane feature disabled??

### ISSUE THREAD

**Issue by Numailia** [BiscuitDevelopment/SkyblockAddons#149]
[Related commit](https://github.com/biscuut/SkyblockAddons/commit/2f879ca527573d744f9a3f318a0a1def2a6c1c6a)

The "Avoid breaking sugar cane base" feature is pretty much mandatory for anyone with a sugarcane farm, unless they want to go through and put slabs everywhere to avoid falling in water. 

Why was this feature disabled? And is it coming back? I can't farm sugarcanes anymore.

**Comment by biscuut** [comment]
@Numailia Unfortunately an admin has requested that the feature be disabled. It wasn't really my decision because they decide what is allowed right :( I made an announcement in my discord about it, so would recommend looking there in the future. Sorry.

**Comment by Keagel** [comment]
We can only hope they don't request the same thing for pumpkin/melon stems...

**Comment by mer2329** [comment]
honestly with melon stems its still required in case a mob spawns, as they trample crops.
