### ISSUE TITLE
When using a Wand Of Healing it adds to digits 2 the end of your health number 

### ISSUE THREAD

**Issue by ThatGravyboat** [BiscuitDevelopment/SkyblockAddons#154]
When using a Wand Of Healing it adds an extra 2 digits to the end of your health and makes the health bar not show health at all until the timer for the healing wand is done.

This is what it looks like on your health bar 
![2019-10-13_17 21 37](https://user-images.githubusercontent.com/26934102/66721470-6c7a7c80-edde-11e9-91ad-ea5f38afcdc3.png)
and this is what it looks like on the normal one
![2019-10-13_17 22 19](https://user-images.githubusercontent.com/26934102/66721488-7ac89880-edde-11e9-9b9b-25d9bce5f176.png)
from what it looks like you're just getting the numbers in the bar so it also includes the 20 thats there and makes the health bar glitch out and things it has 2 more digits that it should have.

**Comment by biscuut** [comment]
Yep i've fixed this yesterday, will be fixed next update.
