### ISSUE TITLE
Jungle Axe cooldown waits for 15 seconds instead of 1.5 seconds

### ISSUE THREAD

**Issue by Keagel** [BiscuitDevelopment/SkyblockAddons#160]
For some reason, when compiling @comniemeer's version it worked fine. Compiling the version that was merged (#145) results in a 15 seconds cooldown instead of 1.5 seconds.

**Comment by biscuut** [comment]
he committed 15,000ms (15s), i have it fixed locally but that was his commit

**Comment by Keagel** [comment]
His version was working for me because I compiled from his repo instead of from his commit. In his repo it is corrected to 1500 instead of 15000 which is why it's working.

**Comment by comniemeer** [comment]
I think biscuut changed it accidentally from "1500l" (long) to "15000" while resolving merge conflicts. In my pull request, it was correct.

**Comment by biscuut** [comment]
Oh, I must be blind. When I was going through the commit I thought you wrote 15001, and I'm like, 15000 looks much more cleaner so I rounded it down. Going back now, I see you wrote 1500 L and not 15001 (I always use uppercase L so I guess I didn't expect it oof )

**Comment by tomocrafter** [comment]
I didn't know you can write 1500L to 1500l before I see this lol

**Comment by Keagel** [comment]
I actually read it as 15001 too which is why I found it weird the version I compiled from comniemeer's repo worked.
