### ISSUE TITLE
Crafting pattern check is bypassed by Mouse Tweaks

### ISSUE THREAD

**Issue by Keagel** [BiscuitDevelopment/SkyblockAddons#162]
This is related to the feature that was just added (#153).

**Comment by tomocrafter** [comment]
Is Mouse Tweaks allowed on Hypixel to use?

**Comment by Keagel** [comment]
To be honest I'm not sure. I went ahead and installed it based on an issue I read here that mentioned it, but I only ever use the shift-click function. Apparently some people use it for PvP which could be an unfair advantage based on Hypixel's rules.

**Comment by biscuut** [comment]
yeah this was fixed in #153 as you mentioned
also i dont think mouse tweaks is officially allowed or anything but so many people use it anyways so  🤷‍♂

**Comment by Keagel** [comment]
I'm not sure I understand you. How was it fixed in #153 when it's the feature I just reported the bug to? If you meant #137, it didn't fix it because the fix that was implemented is for player containers whereas the crafting pattern is in the MixinChest.

**Comment by DidiSkywalker** [comment]
Yea #153 only introduced the feature, not fix compatibility with MouseTweaks, so @biscuut should probably reopen this

**Comment by biscuut** [comment]
ok lol i'm back, and sorry @Keagel I don't know what I was thinking when I closed this, but yes this is a valid issue
