### ISSUE TITLE
Able to drop Spicy Silver Fang from hotbar

### ISSUE THREAD

**Issue by Autonomorantula** [BiscuitDevelopment/SkyblockAddons#163]
SkyblockAddons is supposed to prevent the user from dropping rare items and tools from their hotbar. I tested this and was unable to drop my unenchanted Rapid Wither Bow and my Spicy Rogue Sword enchanted with Telekinesis I, but I was able to drop my Spicy Silver Fang enchanted with Telekinesis I.
![2019-10-19_19 44 47](https://user-images.githubusercontent.com/44717103/67154018-38ed9580-f2a9-11e9-8729-83c94330c79e.png)

**Comment by ViralTaco** [comment]
Rarity lower than rare. Have you tried pressing `L` on it while hovering over it with your mouse in the inventory? I don't know… I'll try to look into it this week-end 😕

**Comment by basketballsmash** [comment]
> Rarity lower than rare. Have you tried pressing `L` on it while hovering over it with your mouse in the inventory? I don't know… I'll try to look into it this week-end 😕

the L is for locking the slot and therefore different than the other option "not to drop rare items"
i will check and see what i notice from the behavior of the setting and what items are affected and what items are not

**Comment by taroj1205** [comment]
The rarity of silver fang is uncommon which is not rare item.

That is nice resource pack... What is that resource pack called?

**Comment by Fl4reon** [comment]
> The rarity of silver fang is uncommon which is not rare item.
> 
> That is nice resource pack... What is that resource pack called?

That's Wynncraft's Official Resource Pack.

**Comment by ILikePlayingGames** [comment]
Yes, the silver fang can be dropped because its rarity is not rare or higher. Please use the slot locking feature instead.
