### ISSUE TITLE
Roman Numeral Replace doesn't work sometimes

### ISSUE THREAD

**Issue by MCGamer00000** [BiscuitDevelopment/SkyblockAddons#164]
So for the roman numeral replacer that turns the roman numerals into numbers, some instances it doesn't work.
Like whenever you change your slot and the item name shows, the item name isn't in numbers its in roman numerals.
(Look at the item name above the health)
![2019-10-20_13 35 24](https://user-images.githubusercontent.com/24983191/67163593-ca5b1700-f33e-11e9-81ae-f4f06ccb8276.png)
![2019-10-20_13 35 26](https://user-images.githubusercontent.com/24983191/67163594-ca5b1700-f33e-11e9-842f-e93f5dfb0ec0.png)

EDIT:
That's a pretty insignificant bug, but there is something about the Roman Numeral Replacer that is pretty bad.
![2019-10-20_18 19 42](https://user-images.githubusercontent.com/24983191/67167301-4026a900-f366-11e9-8758-f3344b7e03e2.png)
Where it says "RARE SWORD" It replaced D with 500. And after turning off the feature, it turned back into the right words.
I'd suggest to only replace if its not the last line of lore, or only replace if there's a space before it. (Or remove D entirely, because almost no items have a level D)

**Comment by DidiSkywalker** [comment]
That's because the replacement code only runs on tooltips, so it actually works as intended. And in my opinion that's enough, because you only get those long lists of enchantments with numerals in tooltips, but I guess it wouldn't be much trouble to also replace them elsewhere.

**Comment by MCGamer00000** [comment]
Your right that its probably an unnecessary feature. Its just a suggestion.

I'll edit it to something more important, today I also just noticed that whenever it says "Rare Sword"  or "Uncommon Wand" it replaced the D  at the end with 500. That's definitely a bug. I'll edit it to talk about that.

**Comment by DidiSkywalker** [comment]
And that was fixed in #141

**Comment by MCGamer00000** [comment]
Yup, you're right. Just didn't see it because a new version hasn't been officially released yet since the pull request.
Closing as issue is resolved.
