### ISSUE TITLE
Game crashing on NullPointerException when breaking netherwart in the Blazing Fortress

### ISSUE THREAD

**Issue by Keagel** [BiscuitDevelopment/SkyblockAddons#173]
It is the breaking part that makes it crash, not the picking up. Telekinesis or not doesn't seem to matter. Killing mobs or breaking glowstone/netherrack doesn't make it crash. I wasn't able to catch the exception with Intellij for some reason, it's on [this line](https://github.com/BiscuitDevelopment/SkyblockAddons/blob/b82db14392cfc0ba8b1d547c2ff3ae91de162f8b/src/main/java/codes/biscuit/skyblockaddons/listeners/RenderListener.java#L610). It seems that `mc.getRenderItem()` produces a `null` result that causes the NullPointerException. I don't understand why it only happens with netherwart.

I'm attaching the log if you think it may help.
[crash-2019-10-28_23.27.11-client.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/3780907/crash-2019-10-28_23.27.11-client.txt)

**Comment by biscuut** [comment]
found the issue its just because brewing stand item != brewing stand block
