### ISSUE TITLE
Skill progress gui element doesn't hide and visual bug

### ISSUE THREAD

**Issue by mtnair** [BiscuitDevelopment/SkyblockAddons#182]
"Added a gui feature that shows skill progress with a gui element which might be more compact and nicer looking than looking at it in the normal action bar."

The gui element stays forever, which I find, is a little bit annoying, and when getting carpentry XP, the crafting table is a little bit dark:
https://i.imgur.com/woOSRro.png

**Comment by TheOttoZone** [comment]
Yeah i have this too and I hope the fix/change it.

**Comment by Mrcubix** [comment]
The gui elements doesn't display the correct amount of x:

For exemple, taking a speed III out of a brewing stand give 300 xp, but the gui element just show "+00" .
When i kill a skeleton, it display "+.4" when i get 6.7 xp without the gui element, just don't use it for now and wait for a patch

**Comment by ILikePlayingGames** [comment]
Was fixed iirc
