### ISSUE TITLE
[Bug] Differents issues in the new 1.4 Update

### ISSUE THREAD

**Issue by Mrcubix** [BiscuitDevelopment/SkyblockAddons#185]
- Skill xp advancement isn't displayed correctly
- A non-full itemstack can't be filled if it's the last Itemstack using the crafting pattern
- Cooldown won't display (for grappling hook at least) if you use it too fast (not holding the click)
- Crafting pattern can be bypassed if you click too fast without mouse tweak (1.8.9 bug with ghost Itemstacks make it happen more often)
- Some enchants doesn't display in the enchant table
- Stop Dropping/Selling Rare Items" not working
- The sound feature while fishing is delayed way too much, making the feature useless when having an high ping
- You can lock empty slot without knowing (no lock icon on, just a sound when clicking)
- The key "L" is now bugged when installing this mod and can't be used for other things than locking slots

If i find new bugs, i'll add them here.

https://imgur.com/a/pAtZT6o / link for a preview of all bugs

**Comment by MCGamer00000** [comment]
I've also had some issues with people just not appearing in game... Like thin air is attacking me, and then other people are hitting thin air.
I think it might have to do with the "Hide far entities in lobby" being bugged.
and there doesn't even seem to be a correlation to it. Its just random players, not everyone.
Would be nice to know if anyone else has this issue.

**Comment by Mrcubix** [comment]
> I've also had some issues with people just not appearing in game... Like thin air is attacking me, and then other people are hitting thin air.
> I think it might have to do with the "Hide far entities in lobby" being bugged.
> and there doesn't even seem to be a correlation to it. Its just random players, not everyone.
> Would be nice to know if anyone else has this issue.

Might have to check that, you're talking about PVP or PVE?

**Comment by MCGamer00000** [comment]
> > I've also had some issues with people just not appearing in game... Like thin air is attacking me, and then other people are hitting thin air.
> > I think it might have to do with the "Hide far entities in lobby" being bugged.
> > and there doesn't even seem to be a correlation to it. Its just random players, not everyone.
> > Would be nice to know if anyone else has this issue.
> 
> Might have to check that, you're talking about PVP or PVE? (or both ? cause i'm not shocked if that's the case at this point).

I was in housing when started happening, and have yet to check in any other server, but its def an issue of not being able to see people that are indeed there.

**Comment by julespopo** [comment]
I have a problem that no one told you about... I'm a left handed so im playing with arrows key and for slot 1 I use the key L... Once ive installed the 1.4.0 skyblock addons, this key doesnt work anymore

**Comment by Mrcubix** [comment]
so that one feature would be enabled and bugged on other servers? might be interesting to check that.

**Comment by Mrcubix** [comment]
> > > I've also had some issues with people just not appearing in game... Like thin air is attacking me, and then other people are hitting thin air.
> > > I think it might have to do with the "Hide far entities in lobby" being bugged.
> > > and there doesn't even seem to be a correlation to it. Its just random players, not everyone.
> > > Would be nice to know if anyone else has this issue.
> > 
> > 
> > Might have to check that, you're talking about PVP or PVE? (or both ? cause i'm not shocked if that's the case at this point).
> 
> I was in housing when started happening (on a pvp house), and have yet to check in any other server, but its def an issue of not being able to see people that are indeed there.

so that one feature would be enabled and bugged on other servers? might be interesting to check that.

**Comment by Mrcubix** [comment]
> I have a problem that no one told you about... I'm a left handed so im playing with arrows key and for slot 1 I use the key L... Once ive installed the 1.4.0 skyblock addons, this key doesnt work anymore

Quand tu va dans les controles, et que tu clique sur la touche comme pour la modifier, clique sur Echap pour la desactiver et regarde si ça marche

**Comment by julespopo** [comment]
> > I have a problem that no one told you about... I'm a left handed so im playing with arrows key and for slot 1 I use the key L... Once ive installed the 1.4.0 skyblock addons, this key doesnt work anymore
> 
> Quand tu va dans les controles, et que tu clique sur la touche comme pour la modifier, clique sur Echap pour la desactiver (ça devrait afficher "None" en anglais ou "Aucun" en Français) et regarde si ça marche

ça m'affiche bien "none", si je bind une autre touche elle fonctionne... qd j'ai unbind la touche L pour le slot 1, et que j'ai fait L a nouveau ingame, rien ne se passe, donc je n'ai pas l'impression que la touche soit utilisée pour quoique ce soit..

**Comment by Mrcubix** [comment]
> > > I have a problem that no one told you about... I'm a left handed so im playing with arrows key and for slot 1 I use the key L... Once ive installed the 1.4.0 skyblock addons, this key doesnt work anymore
> > 
> > 
> > Quand tu va dans les controles, et que tu clique sur la touche comme pour la modifier, clique sur Echap pour la desactiver (ça devrait afficher "None" en anglais ou "Aucun" en Français) et regarde si ça marche
> 
> ça m'affiche bien "none", si je bind une autre touche elle fonctionne... qd j'ai unbind la touche L pour le slot 1, et que j'ai fait L a nouveau ingame, rien ne se passe, donc je n'ai pas l'impression que la touche soit utilisée pour quoique ce soit..

tu as bien désactivé la feature "allow locking slot" dans /sba?

**Comment by julespopo** [comment]
> > > > I have a problem that no one told you about... I'm a left handed so im playing with arrows key and for slot 1 I use the key L... Once ive installed the 1.4.0 skyblock addons, this key doesnt work anymore
> > > 
> > > 
> > > Quand tu va dans les controles, et que tu clique sur la touche comme pour la modifier, clique sur Echap pour la desactiver (ça devrait afficher "None" en anglais ou "Aucun" en Français) et regarde si ça marche
> > 
> > 
> > ça m'affiche bien "none", si je bind une autre touche elle fonctionne... qd j'ai unbind la touche L pour le slot 1, et que j'ai fait L a nouveau ingame, rien ne se passe, donc je n'ai pas l'impression que la touche soit utilisée pour quoique ce soit..
> 
> tu as bien désactivé la feature "allow locking slot" dans /sba?

Oui, j'ai essayé avec "allow locking slot" sans aucune touche définie, et avec S que j'utilise normalement, rien n'y fait..

**Comment by Mrcubix** [comment]
> > > > > I have a problem that no one told you about... I'm a left handed so im playing with arrows key and for slot 1 I use the key L... Once ive installed the 1.4.0 skyblock addons, this key doesnt work anymore
> > > > 
> > > > 
> > > > Quand tu va dans les controles, et que tu clique sur la touche comme pour la modifier, clique sur Echap pour la desactiver (ça devrait afficher "None" en anglais ou "Aucun" en Français) et regarde si ça marche
> > > 
> > > 
> > > ça m'affiche bien "none", si je bind une autre touche elle fonctionne... qd j'ai unbind la touche L pour le slot 1, et que j'ai fait L a nouveau ingame, rien ne se passe, donc je n'ai pas l'impression que la touche soit utilisée pour quoique ce soit..
> > 
> > 
> > tu as bien désactivé la feature "allow locking slot" dans /sba?
> 
> Oui, j'ai essayé avec "allow locking slot" sans aucune touche définie, et avec S que j'utilise normalement, rien n'y fait..

Je l'ai test de mon côté, c'est bien un bug, je l'ai ajouté à la liste et je le report dessuite sur discord

**Comment by julespopo** [comment]
> > > > > > I have a problem that no one told you about... I'm a left handed so im playing with arrows key and for slot 1 I use the key L... Once ive installed the 1.4.0 skyblock addons, this key doesnt work anymore
> > > > > 
> > > > > 
> > > > > Quand tu va dans les controles, et que tu clique sur la touche comme pour la modifier, clique sur Echap pour la desactiver (ça devrait afficher "None" en anglais ou "Aucun" en Français) et regarde si ça marche
> > > > 
> > > > 
> > > > ça m'affiche bien "none", si je bind une autre touche elle fonctionne... qd j'ai unbind la touche L pour le slot 1, et que j'ai fait L a nouveau ingame, rien ne se passe, donc je n'ai pas l'impression que la touche soit utilisée pour quoique ce soit..
> > > 
> > > 
> > > tu as bien désactivé la feature "allow locking slot" dans /sba?
> > 
> > 
> > Oui, j'ai essayé avec "allow locking slot" sans aucune touche définie, et avec S que j'utilise normalement, rien n'y fait..
> 
> Je l'ai test de mon côté, c'est bien un bug, je l'ai ajouté à la liste et je le report dessuite sur discord

niquel merci, continuez le bon boulot, le mod est vraiment super utile...

**Comment by ILikePlayingGames** [comment]
Will check if any of these are still present

**Comment by ILikePlayingGames** [comment]
- Skill xp advancement isn't displayed correctly: fixed
- A non-full itemstack can't be filled if it's the last Itemstack using the crafting pattern: crafting patterns disallowed by Hypixel
- Cooldown won't display (for grappling hook at least) if you use it too fast (not holding the click): can't duplicate
- Crafting pattern can be bypassed if you click too fast without mouse tweak (1.8.9 bug with ghost Itemstacks make it happen more often): crafting patterns disallowed by Hypixel
- Some enchants doesn't display in the enchant table: Enchantment table feature removed due to Hypixel update making it obsolete
- Stop Dropping/Selling Rare Items" not working: fixed
- The sound feature while fishing is delayed way too much, making the feature useless when having an high ping: Feature no longer being maintained, NEU fishing notification is recommended as a replacement
- You can lock empty slot without knowing (no lock icon on, just a sound when clicking): fixed
- The key "L" is now bugged when installing this mod and can't be used for other things than locking slots: Please set the lock slot key to a different key to avoid this
