### ISSUE TITLE
Only Mine Ores in the Deep Caverns feature disabled?

### ISSUE THREAD

**Issue by rangeroverct** [BiscuitDevelopment/SkyblockAddons#190]
This feature is suddenly disabled, why?

**Comment by DidiSkywalker** [comment]
> Disabled skill display & deep caverns features while I [Biscuit] fix em up.


As mentioned in this commit https://github.com/BiscuitDevelopment/SkyblockAddons/commit/f8519b5e5bf5afe71727e0ead4fc22a0cde8f532
