### ISSUE TITLE
New "Choose Crafting Patterns" Incompatible with Mouse Tweaks and Also a feature suggestion

### ISSUE THREAD

**Issue by SirNapkin1334** [BiscuitDevelopment/SkyblockAddons#192]
So, I'm sure you've heard of [Mouse Tweaks](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks). One of the mod's functions allows you to "shift-click" many items into other inventories very quickly, where instead of holding shift and clicking on each stack, you need only hold shift and drag your mouse over all the stacks you want to transfer. This makes crafting much faster. However, with the "Choose Crafting Patterns" feature, if you shift-drag items into the crafting table, they will go in regardless of which pattern you have selected.

Here is a video of me initially shift-clicking, then shift-dragging a few times, and shift-clicking one last time.

![2019-11-04 16-59-07](https://user-images.githubusercontent.com/31591796/68170670-9b8b9600-ff25-11e9-8cf2-dd67f0d21188.gif)

And for the suggestion: perhaps you could add a button by the crafting patterns buttons that will automatically shift-click crafted enchanted items into your inventory, so you don't have to shift-click all the items into the crafting table, and then go up to it and shift-click the crafted item back into your inventory. This would save a lot of time.

**Comment by DidiSkywalker** [comment]
That is caused by multiplayer based lag and there's not much we can do about it. As for the feature, that'd be a macro and not allowed on Hypixel.
See #162 #169 and #184

**Comment by SirNapkin1334** [comment]
Looks like this was fixed in 68ee1e, so I will close this issue.
