### ISSUE TITLE
"L" key does not work

### ISSUE THREAD

**Issue by Autonomorantula** [BiscuitDevelopment/SkyblockAddons#194]
With SkyblockAddons 1.4, the L key does not seem to work for controls. If I set "Strafe Left", "Jump", "Toggle Perspective", or "Attack/Destroy" to the L key, I cannot do those actions when I press the L key. "Edit GUI Locations" and "Settings" do work with the L key.

**Comment by Mrcubix** [comment]
known bug, should be fixed

**Comment by Autonomorantula** [comment]
Update: This bug seems to be fixed.
