### ISSUE TITLE
BUG Minecraft crashes when crafting

### ISSUE THREAD

**Issue by Sunjaeeeee** [BiscuitDevelopment/SkyblockAddons#203]
I use the 5 craft generously (crafting enchanted cobblestone) and when I do it after a while it crashes. I double shift-click my cobble into the boxes instead of individually shift-clicking them in.
Here is the crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (Sk1er Levelhead (1.8.9)-6.4.jar)
  Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  FMLLoadingPlugin (MouseDelayFix-1.0.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 11/8/19 10:44 PM
Description: Updating screen events

java.lang.IndexOutOfBoundsException: Index: 56, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:111)
	at net.minecraft.client.multiplayer.PlayerControllerMP.handler$onWindowClick$zzh000(PlayerControllerMP.java:775)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:691)
	at net.minecraft.client.gui.inventory.GuiChest.func_146984_a(SourceFile:731)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146983_a(GuiContainer.java:732)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java:705)
	at net.minecraft.client.gui.inventory.GuiChest.func_73869_a(SourceFile:674)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:578)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:534)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:111)
	at net.minecraft.client.multiplayer.PlayerControllerMP.handler$onWindowClick$zzh000(PlayerControllerMP.java:775)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:691)
	at net.minecraft.client.gui.inventory.GuiChest.func_146984_a(SourceFile:731)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146983_a(GuiContainer.java:732)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java:705)
	at net.minecraft.client.gui.inventory.GuiChest.func_73869_a(SourceFile:674)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:578)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:534)

-- Affected screen --
Details:
	Screen name: ~~ERROR~~ NullPointerException: null

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['i2r'/4241478, l='MpServer', x=22.60, y=93.00, z=-27.31], EntityOtherPlayerMP['ItsIoana'/7991995, l='MpServer', x=22.59, y=103.00, z=-27.31]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,100.00,0.00 - World: (0,100,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6521 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 114 total; [EntityOtherPlayerMP['ItsIoana'/7991995, l='MpServer', x=22.59, y=103.00, z=-27.31], EntityArmorStand['Armor Stand'/7991913, l='MpServer', x=-1.38, y=99.31, z=15.41], EntityArmorStand['Armor Stand'/7991912, l='MpServer', x=-1.50, y=100.28, z=15.03], EntityArmorStand['Armor Stand'/7991915, l='MpServer', x=-1.59, y=99.53, z=15.00], EntityArmorStand['Armor Stand'/7991914, l='MpServer', x=-1.63, y=99.31, z=14.53], EntityArmorStand['Armor Stand'/7991905, l='MpServer', x=-2.56, y=99.44, z=3.00], EntityArmorStand['Armor Stand'/7991904, l='MpServer', x=-2.72, y=99.44, z=3.13], EntityArmorStand['Armor Stand'/7991907, l='MpServer', x=-2.66, y=99.03, z=3.00], EntityArmorStand['Armor Stand'/7991906, l='MpServer', x=-2.63, y=99.28, z=3.03], EntityArmorStand['Armor Stand'/7991909, l='MpServer', x=-2.66, y=99.97, z=3.03], EntityArmorStand['Armor Stand'/7991908, l='MpServer', x=-2.69, y=99.44, z=2.94], EntityArmorStand['Armor Stand'/7991911, l='MpServer', x=-1.72, y=99.78, z=15.44], EntityArmorStand['Armor Stand'/7991910, l='MpServer', x=-1.72, y=98.53, z=15.44], EntityArmorStand['Armor Stand'/7991897, l='MpServer', x=20.44, y=100.75, z=14.69], EntityArmorStand['Armor Stand'/7991896, l='MpServer', x=20.41, y=100.13, z=14.69], EntityArmorStand['Armor Stand'/7991899, l='MpServer', x=-0.28, y=99.28, z=3.78], EntityArmorStand['Armor Stand'/7991898, l='MpServer', x=20.44, y=99.56, z=13.50], EntityArmorStand['Armor Stand'/7991901, l='MpServer', x=-0.53, y=99.88, z=3.78], EntityArmorStand['Armor Stand'/7991900, l='MpServer', x=0.03, y=99.09, z=3.78], EntityArmorStand['Armor Stand'/7991903, l='MpServer', x=-2.75, y=99.44, z=3.00], EntityArmorStand['Armor Stand'/7991902, l='MpServer', x=-0.28, y=99.00, z=3.78], EntityArmorStand['Armor Stand'/7991889, l='MpServer', x=20.41, y=100.81, z=14.13], EntityArmorStand['Armor Stand'/7991888, l='MpServer', x=20.44, y=100.81, z=12.91], EntityArmorStand['Armor Stand'/7991891, l='MpServer', x=20.41, y=99.50, z=12.34], EntityArmorStand['Armor Stand'/7991890, l='MpServer', x=20.44, y=98.88, z=12.34], EntityArmorStand['Armor Stand'/7991893, l='MpServer', x=20.41, y=100.75, z=12.34], EntityArmorStand['Armor Stand'/7991892, l='MpServer', x=20.44, y=100.13, z=12.34], EntityArmorStand['Armor Stand'/7991895, l='MpServer', x=20.44, y=99.50, z=14.69], EntityArmorStand['Armor Stand'/7991894, l='MpServer', x=20.44, y=98.88, z=14.69], EntityArmorStand['Armor Stand'/7991881, l='MpServer', x=20.41, y=99.56, z=14.13], EntityArmorStand['Armor Stand'/7991880, l='MpServer', x=20.44, y=99.56, z=12.91], EntityArmorStand['Armor Stand'/7991883, l='MpServer', x=20.41, y=100.19, z=13.50], EntityArmorStand['Armor Stand'/7991882, l='MpServer', x=20.44, y=100.19, z=12.94], EntityArmorStand['Armor Stand'/7991885, l='MpServer', x=20.44, y=98.63, z=12.91], EntityArmorStand['Armor Stand'/7991884, l='MpServer', x=20.44, y=100.19, z=14.16], EntityArmorStand['Armor Stand'/7991887, l='MpServer', x=20.41, y=100.81, z=13.50], EntityArmorStand['Armor Stand'/7991886, l='MpServer', x=20.41, y=98.63, z=14.13], EntityItemFrame['entity.ItemFrame.name'/7991873, l='MpServer', x=13.50, y=112.50, z=-11.97], EntityVillager['Villager'/7991872, l='MpServer', x=13.50, y=110.00, z=-11.50], EntityItemFrame['entity.ItemFrame.name'/7991875, l='MpServer', x=5.50, y=101.50, z=-25.97], EntityItemFrame['entity.ItemFrame.name'/7991874, l='MpServer', x=9.50, y=100.50, z=-25.97], EntityArmorStand['Armor Stand'/7991877, l='MpServer', x=20.44, y=98.94, z=12.91], EntityArmorStand['Armor Stand'/7991876, l='MpServer', x=20.41, y=98.94, z=13.50], EntityArmorStand['Armor Stand'/7991879, l='MpServer', x=20.41, y=98.63, z=13.50], EntityArmorStand['Armor Stand'/7991878, l='MpServer', x=20.44, y=98.94, z=14.13], EntityItemFrame['entity.ItemFrame.name'/7991871, l='MpServer', x=12.50, y=100.50, z=-25.97], EntityArmorStand['Armor Stand'/7992323, l='MpServer', x=3.00, y=100.56, z=33.50], EntityArmorStand['Armor Stand'/7992322, l='MpServer', x=3.00, y=100.94, z=33.50], EntityArmorStand['Armor Stand'/7992325, l='MpServer', x=13.50, y=100.94, z=34.00], EntityArmorStand['Armor Stand'/7992326, l='MpServer', x=13.50, y=100.56, z=34.00], EntityArmorStand['§9? §aWarp To §aLime'/7992566, l='MpServer', x=26.50, y=99.44, z=-30.50], EntityPlayerSP['i2r'/4241478, l='MpServer', x=22.60, y=93.00, z=-27.31], EntityArmorStand['Armor Stand'/7992013, l='MpServer', x=13.50, y=110.09, z=-11.50], EntityArmorStand['Armor Stand'/7992012, l='MpServer', x=13.50, y=110.34, z=-11.50], EntityArmorStand['Armor Stand'/7992014, l='MpServer', x=13.50, y=109.84, z=-11.50], EntityArmorStand['Armor Stand'/7991993, l='MpServer', x=-5.50, y=100.00, z=-13.50], EntityArmorStand['Armor Stand'/7991992, l='MpServer', x=-0.50, y=100.00, z=-13.50], EntityOtherPlayerMP['ItsIoana'/7991995, l='MpServer', x=22.59, y=103.00, z=-27.31], EntityArmorStand['Armor Stand'/7991985, l='MpServer', x=-33.50, y=88.59, z=-9.44], EntityArmorStand['Armor Stand'/7991984, l='MpServer', x=-33.50, y=89.97, z=-9.44], EntityArmorStand['Armor Stand'/7991987, l='MpServer', x=-33.50, y=89.31, z=-9.44], EntityArmorStand['Armor Stand'/7991986, l='MpServer', x=-33.50, y=89.56, z=-9.44], EntityArmorStand['Armor Stand'/7991989, l='MpServer', x=-10.50, y=100.00, z=-18.50], EntityArmorStand['Armor Stand'/7991991, l='MpServer', x=-10.50, y=100.00, z=-7.50], EntityArmorStand['Armor Stand'/7991990, l='MpServer', x=-0.50, y=100.00, z=-23.50], EntityArmorStand['Armor Stand'/7991977, l='MpServer', x=-2.34, y=100.13, z=12.22], EntityArmorStand['Armor Stand'/7991976, l='MpServer', x=-2.38, y=99.50, z=12.25], EntityArmorStand['Armor Stand'/7991979, l='MpServer', x=-2.34, y=98.88, z=14.59], EntityArmorStand['Armor Stand'/7991978, l='MpServer', x=-2.38, y=100.75, z=12.22], EntityArmorStand['Armor Stand'/7991981, l='MpServer', x=-2.38, y=100.13, z=14.59], EntityArmorStand['Armor Stand'/7991980, l='MpServer', x=-2.34, y=99.50, z=14.56], EntityArmorStand['Armor Stand'/7991983, l='MpServer', x=-2.34, y=99.56, z=13.41], EntityArmorStand['Armor Stand'/7991982, l='MpServer', x=-2.34, y=100.75, z=14.59], EntityArmorStand['Armor Stand'/7991969, l='MpServer', x=-2.34, y=100.19, z=14.03], EntityArmorStand['Armor Stand'/7991968, l='MpServer', x=-2.38, y=100.19, z=13.41], EntityArmorStand['Armor Stand'/7991971, l='MpServer', x=-2.38, y=98.63, z=14.00], EntityArmorStand['Armor Stand'/7991970, l='MpServer', x=-2.34, y=98.63, z=12.78], EntityArmorStand['Armor Stand'/7991973, l='MpServer', x=-2.34, y=100.81, z=12.78], EntityArmorStand['Armor Stand'/7991972, l='MpServer', x=-2.38, y=100.81, z=13.44], EntityArmorStand['Armor Stand'/7991975, l='MpServer', x=-2.34, y=98.88, z=12.25], EntityArmorStand['Armor Stand'/7991974, l='MpServer', x=-2.38, y=100.81, z=14.00], EntityArmorStand['Armor Stand'/7991961, l='MpServer', x=-2.38, y=98.94, z=13.41], EntityArmorStand['Armor Stand'/7991960, l='MpServer', x=-10.50, y=100.00, z=-23.50], EntityArmorStand['Armor Stand'/7991963, l='MpServer', x=-2.34, y=98.94, z=14.03], EntityArmorStand['Armor Stand'/7991962, l='MpServer', x=-2.34, y=98.94, z=12.78], EntityArmorStand['Armor Stand'/7991965, l='MpServer', x=-2.34, y=99.56, z=12.75], EntityArmorStand['Armor Stand'/7991964, l='MpServer', x=-2.38, y=98.63, z=13.41], EntityArmorStand['Armor Stand'/7991967, l='MpServer', x=-2.34, y=100.19, z=12.78], EntityArmorStand['Armor Stand'/7991966, l='MpServer', x=-2.38, y=99.56, z=14.03], EntityArmorStand['Armor Stand'/7991953, l='MpServer', x=-5.50, y=100.00, z=-23.50], EntityArmorStand['Armor Stand'/7991952, l='MpServer', x=-33.84, y=89.00, z=-10.97], EntityArmorStand['Armor Stand'/7991955, l='MpServer', x=-33.38, y=89.78, z=-12.78], EntityArmorStand['Armor Stand'/7991954, l='MpServer', x=-33.38, y=88.53, z=-12.78], EntityArmorStand['Armor Stand'/7991957, l='MpServer', x=-33.72, y=89.31, z=-12.75], EntityArmorStand['Armor Stand'/7991956, l='MpServer', x=-33.56, y=90.28, z=-12.41], EntityArmorStand['§cNo Destination'/7992468, l='MpServer', x=3.50, y=99.44, z=-30.50], EntityArmorStand['Armor Stand'/7991959, l='MpServer', x=-33.47, y=89.53, z=-12.41], EntityArmorStand['Armor Stand'/7991958, l='MpServer', x=-33.47, y=89.31, z=-11.94], EntityArmorStand['Armor Stand'/7991945, l='MpServer', x=-38.25, y=95.13, z=-11.06], EntityArmorStand['Armor Stand'/7991944, l='MpServer', x=-38.22, y=95.38, z=-11.34], EntityArmorStand['Armor Stand'/7991947, l='MpServer', x=-38.38, y=94.84, z=-11.22], EntityArmorStand['Armor Stand'/7991946, l='MpServer', x=-38.25, y=95.13, z=-11.16], EntityArmorStand['Armor Stand'/7991949, l='MpServer', x=-33.88, y=89.28, z=-10.97], EntityArmorStand['Armor Stand'/7991948, l='MpServer', x=-38.38, y=94.84, z=-11.44], EntityArmorStand['Armor Stand'/7991951, l='MpServer', x=-33.53, y=89.88, z=-10.97], EntityArmorStand['Armor Stand'/7991950, l='MpServer', x=-34.13, y=89.09, z=-10.97], EntityArmorStand['Armor Stand'/7991937, l='MpServer', x=-10.50, y=100.00, z=-13.50], EntityArmorStand['Armor Stand'/7991936, l='MpServer', x=-5.50, y=100.00, z=-18.50], EntityArmorStand['Armor Stand'/7991939, l='MpServer', x=-5.50, y=100.00, z=-7.50], EntityArmorStand['Armor Stand'/7991938, l='MpServer', x=-0.50, y=100.00, z=-18.50], EntityArmorStand['Armor Stand'/7991941, l='MpServer', x=-38.44, y=95.47, z=-11.69], EntityArmorStand['Armor Stand'/7991940, l='MpServer', x=-38.31, y=95.53, z=-11.72], EntityArmorStand['Armor Stand'/7991943, l='MpServer', x=-38.50, y=95.22, z=-11.47], EntityArmorStand['Armor Stand'/7991942, l='MpServer', x=-38.50, y=95.22, z=-11.56]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (Hypixel) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:417)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3114248816 bytes (2969 MB) / 6073352192 bytes (5792 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_I7 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	mousedelayfix{1.0} [MouseDelayFix] (minecraft.jar) 
	UCHIJA	oldanimations{2.4.2} [OldAnimationsMod] (minecraft.jar) 
	UCHIJA	LEVEL_HEAD{6.4} [Sk1er Level Head] (minecraft.jar) 
	UCHIJA	skyblockaddons{1.4.1} [SkyBlock Addons] (SkyblockAddons-1.4.1-for-MC-1.8.9.jar) 
	UCHIJA	fpsdisplaymod{1.0} [FPSDisplayMod] ([1.8.9] CheatBreakerHUD v4.jar) 
	UCHIJA	cpsmod{1.0} [CPSMod] ([1.8.9] CheatBreakerHUD v4.jar) 
	UCHIJA	keystrokesmod{0.1} [KeystrokesMod] ([1.8.9] CheatBreakerHUD v4.jar) 
	UCHIJA	DJTastyMod{1.0} [DJTastyMod] ([1.8.9] DJTastyMod PORT by OFP.jar) 
	UCHIJA	pingtag{4.0} [pingtag] ([1.8.9] PingTag Mod - 4.0.jar) 
	UCHIJA	sidebarmod{2.0} [Sidebar Mod Revamp] ([1.8.9] Sidebar Mod Revamp.jar) 
	UCHIJA	particlemod{1.02} [Particle Mod] ([1.8.9]ParticleMod-1.02.jar) 
	UCHIJA	autogg{2.0.2} [Auto GG] (AutoGG-2.0.2 (1.8.9).jar) 
	UCHIJA	autotip{3.0} [Autotip] (Autotip-3.0 [1.8-1.12.2].jar) 
	UCHIJA	AutoWho{1.0} [AutoWho] (AutoWho-1.0.jar) 
	UCHIJA	HypixelAutocomplete{1.0.0} [Hypixel Autocomplete] (HypixelAutocomplete 1.0.1 (1.8.9).jar) 
	UCHIJA	jmcm{9.5} [James090500's MinecraftCapes Mod] (MinecraftCapes Forge 1.8.9.jar) 
	UCHIJA	orangetogglesprint{1.0} [Orange's Simple ToggleSprint] (Orange's Simple ToggleSprint-1.0.jar) 
	UCHIJA	ProjectL{0.2} [ProjectL] (ProjectL-0.2.jar) 
	UCHIJA	ResourcePackOrganizer{1.0.3} [Resource Pack Organizer] (ResourcePackOrganizer  MC-1.8.9  v1.0.3.jar) 
	UCHIJA	timechanger{1.0} [TimeChanger] (TimeChanger-1.0 (1.8.9).jar) 
	UCHIJA	publictogglechat{1.2.5} [§6Hypixel §7-§a ToggleChat] (ToggleChat-1.2.5-SNAPSHOT.jar) 
	UCHIJA	enhancements{7.7} [Vanilla Enhancements] (Vanilla Enhancements-7.7.jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (Sk1er Levelhead (1.8.9)-6.4.jar)
  club.sk1er.mods.levelhead.forge.transform.ClassTransformer
Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  com.spiderfrog.main.ClassTransformer
FMLLoadingPlugin (MouseDelayFix-1.0.jar)
  io.prplz.mousedelayfix.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.12' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.12, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: §3§lJaba-§b§l10k-§3§lPack.zip, Lithos-Font+v5+for+1.14.4+.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
	The 5zig Mod Version: 3.11.7
	The 5zig Mod Plugins: []
	Forge: true
	GUI: ~~NULL~~
	OptiFine Version: OptiFine_1.8.9_HD_U_I7
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 441.12
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Keagel** [comment]
I have never had a crash happen due to this feature even when clicking pretty fast. Do you have any steps to reproduce the crash?
I'm noticing you're using a few mods that are flagged as prone to incompatibilities so that might be something to consider.

**Comment by PSNRigner** [comment]
This is a vanilla crash which sometimes happens when clicking using hotkeys (1-9). Never found why that's happening yet

**Comment by Sunjaeeeee** [comment]
This never happened when using just forge without sba (using everything else)
this only happens after i craft about 20 double chests worth of cobble stone

**Comment by Sunjaeeeee** [comment]
java.lang.IndexOutOfBoundsException: Index: 56, Size: 45
is the main reason it crashed and the index can change from time to time to 69 or another number
The size is consistent though

**Comment by tomocrafter** [comment]
Looks like it is crash that sometimes happen even on Vanilla.
