### ISSUE TITLE
Add support for Discord Rich Presence

### ISSUE THREAD

**Issue by LeaPhant** [BiscuitDevelopment/SkyblockAddons#220]
Even though there is a Hypixel Rich Presence mod already, having support specifically for SkyBlock with more detailed data would be nice.

This could include your current player stats (HP, Defense, etc.), coins in your purse and the area you're in. There's probably more interesting stuff to add which I haven't listed here, so feel free to send suggestions!

**Comment by MartinNemi03** [comment]
Also there could be option to show your current item in hand with the small icon, but maybe that's too much, since Discord Application for Rich Presence can handle only like 250 images.. But hey, it would be cool

**Comment by DidiSkywalker** [comment]
Awesome suggestion, I would love to implement it!
So far I've got these ideas:
* Current Location
* Purse
* Stats
* Zealot Counter
* Held Item
* Skyblock Time
* Current Profile (not sure about this one)
* Generic status like 'In Game', 'Mining', 'Grinding'

And for the icon, maybe if we can find an artist we could have cool custom icons for the Skyblock locations, or maybe just have a bunch of preset Skyblock stuff like the Dragon Armor skulls, a Jerry head and whatnot that people could choose from.

**Comment by biscuut** [comment]
oh my god yes

**Comment by biscuut** [comment]
Alright we now have this done in 1.5.0 thanks to Didi! I also added some more features on top, and i'll be adding more statuses in the future ^^
