### ISSUE TITLE
Color of chat messages

### ISSUE THREAD

**Issue by MCGamer00000** [BiscuitDevelopment/SkyblockAddons#235]
Forge version: 1.8.9-forge1.8.9-11.15.1.1722
SkyblockAddons 1.4.2, no other mods

Just look
![2019-12-21_22 37 31](https://user-images.githubusercontent.com/24983191/71316732-1449a180-2443-11ea-89dc-9473591759fd.png)

So I've seen this before. Below is a proposed fix.

With 1.8, the chat was changed so that messages are split into parts. The "correct" way of coloring now, is to select the part that has the text, and set the color of the text to be red, instead of just appending &c to the beginning of the text.

I'll just show a bit of pseudo code.
Old: (I know, &c won't work, just pretend it will)
``player.sendMessage("&cThis is red!");``
New:
``TextComponent msg = new TextComponent("This is red!");``
``msg.setColor(ChatColor.RED);``
``player.sendMessage(msg);``
It's something like that atleast. I usually program on the server side, so it might not be this exactly, but the idea still holds. The old way still is valid, just it can result in what you are seeing in the screenshot. This new way should fix it.

Or, I could be completely wrong and its something else... never know.

**Comment by biscuut** [comment]
It's a forge bug, it exists in the recommended version of forge but not the latest one. If you update it'll fix it . (idk why they recommend the recommended version )
