### ISSUE TITLE
GUI Transformer doesn't called super method

### ISSUE THREAD

**Issue by SteveKunG** [BiscuitDevelopment/SkyblockAddons#257]
**Describe the bug**
Title, Causing other mods injection (mixin) not working such as, `updateScreen()`

For example, If you add GuiTextField into GuiChest and want GuiTextField update cursor. it doesn't work.

Simple fix maybe
```
        list.add(new VarInsnNode(Opcodes.ALOAD, 0));
        list.add(new MethodInsnNode(Opcodes.INVOKESPECIAL, "net/minecraft/client/gui/inventory/GuiContainer", "updateScreen",
                "()V", false)); // net/minecraft/client/gui/GuiScreen.updateScreen()V
```

Using SBA 1.5.0-b4-dev

**Additional info**
Add super() call to the transformers.

~~Also there's no way to render backpack on custom GuiScreen obj.~~
Nevermind, I fixed it on my side.

**Comment by biscuut** [comment]
Fixed for the next beta, thank you for catching this!
