### ISSUE TITLE
Game crashes on start

### ISSUE THREAD

**Issue by lbauer-code** [BiscuitDevelopment/SkyblockAddons#259]
When I start Minecraft (MultiMc launcher) with the newest build of Sba (I built it from the current sourcecode on Github on my own) the game crashes.

Crashreport:
[crash-2020-02-22_16.47.20-client.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/4239568/crash-2020-02-22_16.47.20-client.txt)

I am also using a lot of other mods:
```
Mods:
  [✔️] [1.8.9] fncompassmod-1.0
  [✔️] [1.8.9] GlintColorizer - 1.0
  [✔️] [1.8.9] Perspective Mod-3.0
  [✔️] [1.8.9] Sidebar Mod Revamp
  [✔️] Auto.MyPosition-2.0
  [✔️] AutoGG-2.0.4 (1.8.9)
  [✔️] BetterTab-v1.0
  [✔️] Compact Chat-1.2 (1.8.9)
  [✔️] fragfix-1.0
  [✔️] Hypixel Autocomplete-1.0 (1.8.9)
  [✔️] killeffects-0.0.2
  [✔️] Levelhead-7.0.2 (1.8.9)
  [✔️] LobbySounds-1.0 (1.8.9)
  [✔️] MouseDelayFix-1.0
  [✔️] OptiFine 1.8.9 HD U I7
  [✔️] Popup Events-1.2.2 (1.8.9)
  [✔️] Scrollable Tooltips-1.1 (1.8.9)
  [✔️] SkyblockAddons-1.5.0-b4-for-MC-1.8.9
  [✔️] The.5zig.Mod.v3.12.5.for.Minecraft.1.8.9
  [✔️] TimeChanger 1.8
  [📁] togglechat (folder)
  [✔️] ToggleChat-2.1.0-SNAPSHOT
  [✔️] Winter Weather-1.0 (1.8.9)
  [✔️] Xaeros_Minimap_20.4.0_Forge_1.8.9
```

Maybe the bug is caused by me lol, cause I maybe compiled the mod in a wrong way.
But I only cloned the repo, opend it as Intellij project(gradle project) and run the gradle task jar

**Comment by lbauer-code** [comment]
I did a bit more testing and with the full release 1.4.2 the Game also crashes, but a bit later and with an other error. So I think it is likely caused by the oter mods I'm using xD lol
[crash-2020-02-22_17.07.24-client.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/4239580/crash-2020-02-22_17.07.24-client.txt)

**Comment by lbauer-code** [comment]
After a bit more testing, it seems to happen with all versions of SbA.

**Comment by lbauer-code** [comment]
Lol after I disabled all mods, it is still crashing

**Comment by lbauer-code** [comment]
After I deleted also all the mods it is still not working

**Comment by lbauer-code** [comment]
Also in a new Instance of Multimc it keeps crashing.

**Comment by lbauer-code** [comment]
The releas version 1.4.2 (and the older versions) are working fine in an empty instanceof multimc, so there is an error with the latest source code and multimc and also an error with some of the other mods I use

**Comment by lbauer-code** [comment]
So now I've got Sba 1.4.2 work with all the other mods. I only deleted the file "skyblockaddons.cfg" and "skyblockaddons_persistent.cfg"

**Comment by Berisan** [comment]
To compile the mod you need to use the `build` Gradle task.

**Comment by lbauer-code** [comment]
Right, that should fix the issue, I'm so stupid lol 
It's been a long time since I was used to programm mods. xD
