### ISSUE TITLE
Anyway could this be a Hyperium Addon??[Request]

### ISSUE THREAD

**Issue by PurpShell** [BiscuitDevelopment/SkyblockAddons#262]
**Describe the solution you'd like**
It just opens more ground up.

**Describe alternatives you've considered, if any**
idk

**Comment by SirNapkin1334** [comment]
I vote no. Unless someone can create a script that can compile source into an addon. Otherwise, it's just too inconvenient.

**Comment by ILikePlayingGames** [comment]
Sorry for the very delayed response. We decided that we won't be officially supporting clients anymore after stopping support for Labymod. It was becoming too complex. We currently only support Forge.
