### ISSUE TITLE
Build Version for any newer Minecraft and Forge Version

### ISSUE THREAD

**Issue by svalcken** [BiscuitDevelopment/SkyblockAddons#272]
Hello, is planned to make Versions for newer Minecraft and Forge Version, like 1.14, 1.15, 1.15.2, and any other newer as 1.8.9?

The newer Minecraft Version has a little bit better performance.

Thanks

Sascha

**Comment by ILikePlayingGames** [comment]
Yes, there are plans to make a 1.12 version so far. We're focusing on finishing up v1.5.0 now but we'll probably work on porting to newer versions after we release it.

**Comment by kotyk7** [comment]
Is there a chance for 1.15 version and for 1.16 when it will release?

**Comment by ILikePlayingGames** [comment]
We are planning to support multiple newer versions in the future so it's possible, but I'm not sure which versions (other than 1.12) we'll support and when yet.

**Comment by kotyk7** [comment]
Okay, thanks for info

**Comment by ILikePlayingGames** [comment]
We are planning to support Minecraft versions 1.8.9, 1.12.2, 1.15.2, and 1.16.2. Work will be starting soon on a port to 1.12.2.

**Comment by Div-100** [comment]
> We are planning to support Minecraft versions 1.8.9, 1.12.2, 1.15.2, and 1.16.2. Work will be starting soon on a port to 1.12.2.

Been quite some time

**Comment by ILikePlayingGames** [comment]
Sorry, it won't happen anytime soon as it'll require a full rewrite, Biscuit has left and I have very limited time to maintain the mod.
