### ISSUE TITLE
[Bug] End Chest Zealot

### ISSUE THREAD

**Issue by Dolphin0xyz** [BiscuitDevelopment/SkyblockAddons#275]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Enable green end chest zealot feature 
2. Go to the Dragon Nest on the End Island
3. Find a zealot holding and end chest
4. End chest appears normal instead of green

**Expected behavior**
The end chest held by the zealot should appear as a solid green block

**System Information**
 - OS: Windows 10
 - Mod Loader: Forge
 - Minecraft Version/Mod Loader Version: 1.8.9 - 11.15.1.17222
 - SkyblockAddons Version 1.5.0 b8

**Other Installed Mods**
-Powns'Skyblock Exp Mod 1.1
-SBItemRename 1.0
-Better HUD 1.3.7
-Block Overlay 3.2
-Skypixel 0.0.6
-Zealot Counter 1.3.0

**Comment by biscuut** [comment]
Got it thanks <3 Should be fixed in the next beta
