### ISSUE TITLE
Please add a item for stop to drop. item name is [Maddox Batphone][Request]

### ISSUE THREAD

**Issue by soundofhorizon** [BiscuitDevelopment/SkyblockAddons#280]
**Is your feature request related to a problem? If so, please describe.**
I drop item when I don`t consider that. sba is so help that stop these action. but maddox batphone is not supported this.

**Describe the solution you'd like**
Maddox batphone add for can`t drop

**Describe alternatives you've considered, if any**

**Additional info**
if user select item for can drop or can`t drop item, sba will better mod for Skyblock XD

**Comment by ILikePlayingGames** [comment]
Fixed in commit d2cd876f86853e6b17072ab543d9dd9563b6e64d.

The fix will be included in v1.5.0.
