### ISSUE TITLE
[Bug] Base defense shown on defense indicator instead of zero when wearing mastiff armor

### ISSUE THREAD

**Issue by IssaYT** [BiscuitDevelopment/SkyblockAddons#285]
**Describe the bug**
When you use full mastiff armor the mod shows base defence instead of Zero (reduced defence)

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
Just wear full mastiff armor

**Expected behavior**
**Screenshots**
![2020-04-27_16 24 58](https://user-images.githubusercontent.com/52703967/80390016-c850b280-88a3-11ea-8afa-5a80572229ac.png)
![2020-04-27_16 25 05](https://user-images.githubusercontent.com/52703967/80390022-c981df80-88a3-11ea-84df-8cf4b8b41807.png)

**System Information**
 - OS: Win10
 - Mod Loader: Forge
 - Minecraft Version/Mod Loader Version [e.g. 1.8.9 - 11.15.1.2318]
 - SkyblockAddons Version 1.5.0-beta.17

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Optifine I7 Ultra

**Additional info**

**Comment by ILikePlayingGames** [comment]
Fixed in commit 62f06ae15cdb8bd54b0cb1e861e7ccc16ca154f3.

The fix will be included in v1.5.0
