### ISSUE TITLE
[Request] An Option To Disable Teleport Pad Messages

### ISSUE THREAD

**Issue by wincheat02** [BiscuitDevelopment/SkyblockAddons#303]
Basically the same thing as you did for magical mushroom soup but for teleport pads.

**Comment by Charzard4261** [comment]
Biscuit wants suggestions put on https://skyblockaddons.featureupvote.com to stop duplicate suggestions. Also, this should be coming in the next update.

**Comment by biscuut** [comment]
Done, thanks for the request!
