### ISSUE TITLE
Changes not being saved[Bug]

### ISSUE THREAD

**Issue by BadPingHere** [BiscuitDevelopment/SkyblockAddons#311]
**Describe the bug**
The changes you make (gui, turing something on/of) is not saving after minecraft is closed.
**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Make any changes
2. Close client
3. Reopen client

**Expected behavior**
What I expect to happen is to autosave what I have changed

**Screenshots**

**System Information**
 - OS: Windows 10
 - Mod Loader: Forge
 - Minecraft Version/Mod Loader Version 1.8.9
 - SkyblockAddons Version 1.5.0

**Other Installed Mods**
SkyblockAddons-1.8.9-1.5.0, PlayerAPI-1.8.9-1.0, Patcher-1.2 (1.8.9), OptiFine_1.8.9_HD_U_L5, Keystrokes-8.0.2 (1.8.9), Join Message Hider-2.1 (1.8.9), Frames+ 2.0 BETA Build 18 [1.8.9] (1), ChromaHUD-3.0 (1.8.9), BetterFps-1.2.0, Better FPS Limiter-1.0 (1.8.9), Autotip-3.0.1 [1.8-1.12.2], AutoGG-3.3 (1.8.9), [1.8.9] Sidebar Mod Revamp, [1.8.9] Powns ToggleSneak Edit, SkyblockExtras-1.6.0.1

**Comment by biscuut** [comment]
Should be fixed in 1.5.1, thanks!
