### ISSUE TITLE
Build version for 1.15.2 [Request]

### ISSUE THREAD

**Issue by Mehzi** [BiscuitDevelopment/SkyblockAddons#315]
Is a port/upgrade to 1.15.2 under consideration or in the works right now? Currently, the hard limitation to 1.8.9 feels pretty rough with all the client optimization that we miss in 1.15.2

**Comment by ILikePlayingGames** [comment]
I'm not sure about 1.15.2 specifically, but we do have plans to make the mod compatible with multiple Minecraft versions. We haven't begun working on it yet so it might be a while.

**Comment by ILikePlayingGames** [comment]
Sorry for the very delayed response. We aren't planning to support 1.15.2 but we do plan to support 1.16. I'm not sure when it will happen though. We're currently working on v1.6.0 and cleaning up the code.
