### ISSUE TITLE
Bow and Fishing Rod Texturing Bug

### ISSUE THREAD

**Issue by ic22487** [BiscuitDevelopment/SkyblockAddons#316]
**Describe the bug**
Items that have multiple stages (Bows, Fishing rods, etc) dont show those stages while being used with mcpatcher textures

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. download a skyblock resource pack
2. shoot a bow/fire a grappling hook
3. See error

**Expected behavior**
Bow/fishing rod texture should change while being used 

**System Information**
 - OS: OS X Catalina
 - Mod Loader: Forge
 - Minecraft Version/Mod Loader Version 1.8.9
 - SkyblockAddons Version 1.5

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Optifine 1.8.9

**Comment by biscuut** [comment]
This seems to be an issue with Optifine L5, best check out the issue they have open over there: https://github.com/sp614x/optifine/issues/3095
