### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by odnahaon** [BiscuitDevelopment/SkyblockAddons#317]
**Describe the bug**
Discord Rich Presence doesn't display on Ubuntu

**To Reproduce**
1. Run Ubuntu 18.04 and have Discord client
2. Join Skyblock with Skyblock Addons 1.5.0 and Forge
3. Make sure Discord Rich Presence is on in the Skyblock menu and not set to "None"
4. Check your Discord profile

**Expected behavior**
Expected Discord to show a Rich Presence status saying "Playing Skyblock" and other info

**Screenshots**
![Screenshot from 2020-06-22 12-11-44](https://user-images.githubusercontent.com/52327396/85326161-ad548600-b481-11ea-9409-fb2420d34ad4.png)
![Screenshot from 2020-06-22 12-11-51](https://user-images.githubusercontent.com/52327396/85326528-497e8d00-b482-11ea-8248-dff1ff0f9fbb.png)
Sceenshots to show that Discord Rich Presence is on in the mod
![Screenshot from 2020-06-22 12-13-24](https://user-images.githubusercontent.com/52327396/85326354-fe647a00-b481-11ea-8314-bfc5398b73f4.png)
And screenshot to show that nothing shows up on my profile (blacked out name and picture for privacy)

**Crash Report**
Didn't crash, but here's the log anyways:
[latest.log](https://github.com/BiscuitDevelopment/SkyblockAddons/files/4815127/latest.log)

**System Information**
 - OS: Ubuntu 18.04
 - Mod Loader: Forge
 - Minecraft Version/Mod Loader Version: 1.8.9 - 11.15.1.2318
 - SkyblockAddons Version 1.5.0

**Other Installed Mods**
- Optifine 1.8.9_HD_U_L5 (latest at time of writing)
- Was at first tested with other mods, but problem persists after removal

**Comment by biscuut** [comment]
@odnahaon Does this still occur with v1.5.1?

**Comment by odnahaon** [comment]
Issue fixed in 1.5.1, thanks! Doesn't seem compatible with 5zig but I can live without it.
