### ISSUE TITLE
[Bug] Version 1.5.1 creates "Libraries" folder on D drive

### ISSUE THREAD

**Issue by oplexz** [BiscuitDevelopment/SkyblockAddons#320]
**Describe the bug**
I updated to version 1.5.1 (from 1.5.0) today, and noticed a "Libraries" folder on my D drive. Tracked down that it was indeed SBA creating the folder and the files inside it, rolled back to 1.5.0 and this folder didn't appear.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Install SkyblockAddons 1.5.1
2. Launch the game
3. Watch the folder "Libraries" appear on your D drive

**Screenshots**
![image](https://user-images.githubusercontent.com/12859907/85842784-e7d36100-b7a8-11ea-9669-b7dcca2b6423.png)

**System Information**
 - OS: Windows 10 version 1809
 - Mod Loader: Forge
 - Minecraft Version/Mod Loader Version: 1.8.9 - 11.15.1.2318
 - SkyblockAddons Version: 1.5.1

**Comment by DJtheRedstoner** [comment]
Looks like biscuit removed the `isObfuscated` check and hardcoded the libraries path so be could debug asm in non development environment. He should fix this soon.

**Comment by biscuut** [comment]
Yeah my bad, it was a debug I left in, I've fixed it since. Woops!
