### ISSUE TITLE
[Bug] Saves not being changed, v1.5.1

### ISSUE THREAD

**Issue by AnotherGuy19** [BiscuitDevelopment/SkyblockAddons#322]
**Describe the bug**
Same issue report of #311 , gui / feature changes wont save once restarting the client

**To Reproduce**
Steps to reproduce the behaviour (how did you get this bug to occur):
1. Save any changes in menu
2. Close the client by clicking the quit button
3. Restart the client
4. Everything reset to default

**Expected behaviour**
Same as #311 , I'm expected the gui locations / feature changes in my client

**Screenshots**

**System Information**
 - OS: Windows 10
 - Mod Loader: Forge
 - Minecraft Version/Mod Loader Version: 1.8.9
 - SkyblockAddons Version: 1.5.1

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- MouseDelayFix 1.0
- BetterFPSLimiter 1.0
- KeystrokesMod 8.0.2
- MemoryFix 0.3

**Comment by biscuut** [comment]
Can you attach your logs in case there's been some sort of error?

**Comment by AnotherGuy19** [comment]
alright sorry here's the [logs](https://pastebin.com/pfLnFFfB) when I start the client, dunno why every time it get reset to default ;/

**Comment by biscuut** [comment]
Could you send your logs after you try saving the config, for example open the /sba menu, toggle something, close it, and then send me logs?

**Comment by AnotherGuy19** [comment]
Nevermind, it seems the mod is working fine. I tried to delete the skyblockaddons file in the config folder. It works again.
