### ISSUE TITLE
[Bug] Weird Usb Bug maked a Libraries Folder

### ISSUE THREAD

**Issue by Stirpe4me** [BiscuitDevelopment/SkyblockAddons#327]
**Describe the bug**
When I Run Forge (Ver 11.15.1.2318) and Sba It always makes a libraies folder on my usb 3.0. I do have it as NTSF, so its faster and is it a USB 3.0, but this happened recently, and it only happens with Sba, I tried Vanilla, nothing, forge 1.8.9 no mods, nothing, but when yours is the only mod, it happens 100% of the time. Im not mad, and I hope you dont take this the wrong way, Ill upload the folder so u can see.
[Libraries.zip](https://github.com/BiscuitDevelopment/SkyblockAddons/files/4874077/Libraries.zip)

Btw Sba Ver. is 1.5.1

**Comment by biscuut** [comment]
Hi there, yes this is due to a mistake, I accidentally left in saving some harmless debug files! If you want to fix this, just redownload the latest version, but otherwise it should be fixed in the next patch as well. Sorry!

**Comment by oplexz** [comment]
The issue was fixed in version 1.5.2, requesting to close this issue.
