### ISSUE TITLE
[Bug] texture pack does not work

### ISSUE THREAD

**Issue by ilya731** [BiscuitDevelopment/SkyblockAddons#329]
texture pack does not work with the skyblock addons 1.8.9 mod (I tried different texture packs)
(texture packs don't work specifically for skyblock)

**Comment by xWafl** [comment]
Do you have any other info? Packs work fine for me.

**Comment by ilya731** [comment]
No

**Comment by ILikePlayingGames** [comment]
Which texture pack are you using? Do you have Optifine installed?

**Comment by ILikePlayingGames** [comment]
Closed since requested information wasn’t given
