### ISSUE TITLE
[Bug] SBA Menu and Item Frame Issues

### ISSUE THREAD

**Issue by PureAspiration** [BiscuitDevelopment/SkyblockAddons#342]
This may be a mod conflict, check mods below. Also, not screenshots are shown because the screenshots cannot load.

**Issue**
In the 1.5.2 version, doing /sba or clicking the button in the escape menu will load a blank sba menu.

As well as that, if you enable the feature "Ignore Clicks on Item Frames", the feature does not work.

**To Reproduce**
_Sba Menu Bug_
1. Type /SBA
2. See error

_Item Frame Bug_
1. Type /SBA
2. Search "Item"
3. Enable "Ignore Clicks On Item Frames"
4. Break/Rotate Items in Item Frames

**Expected behavior**
Display an SBA menu with all the features on the screen.
Lock item frame movement and show name tag.

**System Information**
OS: Windows 10
Mod Loader: Forge
Minecraft Version/Mod Loader Version: 1.8.9 - 11.15.1.2318
SkyblockAddons Version: v1.5.2

**Other Installed Mods**
- Sidebar Mod Revamp
- Autocorrect 1.0
- Auto GG 2.0.4
- Autotip 3.0.1
- BetterFPS 1.2.0
- Block Overlay
- Compact Chat 1.1
- Hypixel Autocomplete 1.0.1
- MemoryFix 0.3
- Mouse Delay Fix 1.0
- No Close My Chat
- Optifine 1.8.9 HD_U_L5
- Orange's 1.7 Animations 6.7
- Quickplay 2.0.3
- Replaymod 2.3.1
- Skyblock Addons 1.5.2
- TheQuestingMod 2.7
- Torohealth 7
- Vanilla Enhancements 7.7
- Zealot Counter 1.2.2

**Comment by biscuut** [comment]
This is strange, will probably need some sort of logs to see what the issue is

**Comment by PureAspiration** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/67492504/89720602-df1cae80-da27-11ea-9c92-e2d9256977c7.png)
![Screenshot_2](https://user-images.githubusercontent.com/67492504/89720605-e0e67200-da27-11ea-89c9-2e0adc4a4f39.png)

After opening the GUI, the logs go blank for like 1000 lines

**Comment by Phoube** [comment]
Unfortunately, we had to remove this feature in sba 1.6.0 due to Hypixel's modified mod guidelines. See issue #517
