### ISSUE TITLE
[Bug] Invisible boss/dungeon loot

### ISSUE THREAD

**Issue by steve6472** [BiscuitDevelopment/SkyblockAddons#343]
**Describe the bug**
Item loot from bosses/dungeon chests is invisible with Hide Skeleton's Helmet Bones setting enabled.
Problem also occurs with skeletons in dungeons either when spawning or combining.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Enable 'Hide Skeleton's Helmet Bones'.
2. Kill Magma boss or get loot from dungeon.
3. Items dropped are not visible.

**Expected behavior**
Any other items that are not bones from Skeleton's Helmet would be visible.

**Screenshots**
(Chat triggers renders items hitboxes with aqua color)

With 'Hide Skeleton's Helmet Bones' enabled:
![2020-07-23_16 57 37](https://user-images.githubusercontent.com/20379161/88302169-d167e900-cd05-11ea-872d-cdfff2264fb6.png)

With 'Hide Skeleton's Helmet Bones' disabled:
![2020-07-23_16 57 39](https://user-images.githubusercontent.com/20379161/88302215-dd53ab00-cd05-11ea-9ed3-a7cbfb034ffa.png)

**System Information**
 - OS: Windows 10
 - Mod Loader:  Forge
 - Minecraft Version/Mod Loader Version: 1.8.9 - 11.15.1.2318
 - SkyblockAddons Version: 1.5.2

**Other Installed Mods**
- Optifine
- ChatTriggers
- bunch of others, they have no effect on this bug.

**Additional info**
Problem lies in [RenderManagerHook](https://github.com/BiscuitDevelopment/SkyblockAddons/blob/88a8f9452d5434322ce6b589a460e42594d0b88a/src/main/java/codes/biscuit/skyblockaddons/asm/hooks/RenderManagerHook.java#L25) class.
If the armor stand the item is riding is invisible, render of the item will be canceled. Checking if the item is bone would fix most of the problems.

**Comment by ILikePlayingGames** [comment]
Thanks for the report! We fixed this and it will be included in the dungeons update.
