### ISSUE TITLE
[Bug] Discord Rich Presence stays after uninstalling the mod

### ISSUE THREAD

**Issue by Polarize69** [BiscuitDevelopment/SkyblockAddons#344]
For some reason rich presence is stuck on Skyblock island after uninstalling Sba. i tried installing it back and turning it on and off but still nothing happened. Can u pls fix this? the time also just keeps going up and up.

**Reproduce**
Can't reproduce idk how this even happened.

**Supposed to happen**
Supposed to show where i am in hypixel.

**System Information**
 - OS: [e.g. Windows 10]
 - Mod Loader: Forge
 - Minecraft Version/Mod Loader Version: 1.8.9 , forge 11.15.1.1722
 - SkyblockAddons Versio: latest

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
no other mods installed

**Comment by ILikePlayingGames** [comment]
Can you please press `CTRL + R` in Discord to refresh it and see if the rich presence goes away? If not, can you please restart your PC?

**Comment by ILikePlayingGames** [comment]
This issue has been closed since I have not received a response from you. If you are still facing this issue, please make a new report.
