### ISSUE TITLE
[Request] Keep the dungeon map on screen when the player is holding a bow

### ISSUE THREAD

**Issue by ILikePlayingGames** [BiscuitDevelopment/SkyblockAddons#347]
**Describe the bug**
Holding a bow in dungeons causes the dungeon map to disappear.

**Comment by Witelitening** [comment]
this is intentional design for quiver. The mod cant view the map when its replaced by quiver

**Comment by ILikePlayingGames** [comment]
Oh yeah you're right. This should be tagged feature request instead.

**Comment by ILikePlayingGames** [comment]
Closed, [moved to FeatureUpvote](https://skyblockaddons.featureupvote.com/suggestions/111593/keep-the-dungeon-map-on-screen-while-player-is-holding-a-bow)
