### ISSUE TITLE
[Bug] Dungeon map not showing up

### ISSUE THREAD

**Issue by llamasgobrrr** [BiscuitDevelopment/SkyblockAddons#352]
Hey i downloaded the mod but the dungeon map is not showing up. if im not using the correct version please tell me which one is working.

**Comment by ILikePlayingGames** [comment]
Are you using the beta? The dungeon map hasn't been released yet, it's only available in the beta.

**Comment by ILikePlayingGames** [comment]
Closed since requested information was not provided
