### ISSUE TITLE
[Bug] Mod setting reset everytime I close the game and re launch it

### ISSUE THREAD

**Issue by Elasder123** [BiscuitDevelopment/SkyblockAddons#385]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
So I start Minecraft it loads up and the game works but after I change settings in the skyblock addons mod and then close Minecraft completely and launch the game again my setting reset and I need to turn on the mod settings again and It has bothered me a lot so please fix this

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Launch Minecraft with forge 
2. Start playing hypixel skyblock
3. Change some setting in the mod like turning on the magma boss timer or mana health bar
4. close Minecraft completely
5.launch it again and boom settings reset

**Expected behavior**
Setting go back like I never changed them when launching the game after closing it so the mod settings never save

**Screenshots**

**Crash Report**
If your game crashed, please paste your crash report here.

**System Information**
 - OS: Windows
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.1722
 - SkyblockAddons Version: 1.5.2

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- [1.8.9] Sidebar Mod Revamp
- Better FPS Limiter-1.0 (1.8.9)
- BetterFps-1.2.0
- Keystrokes-8.0.2 (1.8.9)
- OofMod-2.0.2 (1.8.9)
- OptiFine_1.8.9_HD_U_L5
- Patcher-1.3 (1.8.9)

**Additional info**

**Comment by ILikePlayingGames** [comment]
Hi, please uninstall Better FPS Limiter-1.0. This mod prevents SBA from saving its settings.

**Comment by Elasder123** [comment]
> 
> 
> Hi, please uninstall Better FPS Limiter-1.0. This mod prevents SBA from saving its settings.

that worked tysm
