### ISSUE TITLE
[Enhancement] Highlight tier 6/4 enchantments

### ISSUE THREAD

**Issue by ILikePlayingGames** [BiscuitDevelopment/SkyblockAddons#390]
Show tier 6 or 4 enchantments in a different color when hovering over an enchanted item (similar to in sky.lea) to make it easier to find them

FeatureUpvote page: https://skyblockaddons.featureupvote.com/suggestions/94559/highlight-tier-64-enchantments

**Comment by PCRGaming** [comment]
my mod does exactly that and just that :
https://github.com/PCRGaming/EnchantMent-Mod/releases/tag/v1.0

**Comment by RobotHanzo** [comment]
> my mod does exactly that and just that :
> https://github.com/PCRGaming/EnchantMent-Mod/releases/tag/v1.0

1. This PR's feature is already added, no further information is necessary unless its a addition to it
2. This isn't the right place to promote your mod

**Comment by ILikePlayingGames** [comment]
Oops, I forgot to close this. Thanks for reminding me with the notification!
