### ISSUE TITLE
[Bug] Discord RPC always on

### ISSUE THREAD

**Issue by skyblockz** [BiscuitDevelopment/SkyblockAddons#392]
**Describe the bug**
Discord RPC doesn't stop when disconnected from hypixel (or when quitting skyblock), even when you close the game

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Enable Discord RPC
2. Disconnect from Hypixel
3. Go to discord and your profile 
4. See your location go unknown

**Expected behavior**
Closes the RPC 

**Screenshots**
None
**Crash Report**
None

**System Information**
 - OS: Windows 10 Dev Channel 
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.5.2

**Other Installed Mods**
All the mods in Refractions modpack

**Comment by filipwtf** [comment]
I assume that's to do with discord caching, you can open dev tools (crtl +shift +i )and press "Disable Cache" and restart you discord and the rpc should not show, make sure to turn caching back on after.

**Comment by skyblockz** [comment]
Indeed it was to do with the cache, after one time clear it no longer happens
