### ISSUE TITLE
[Bug] Reforge doesn't work with Accessory Bag

### ISSUE THREAD

**Issue by iHDeveloper** [BiscuitDevelopment/SkyblockAddons#396]
The reforge feature doesn't work on **Accessory Bag**.
I'm not sure about the other bags.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Go to 'Blacksmith'
2. Click on 'Accessory Bag Reforging'
3. See error

**Expected behavior**
The reforge filter should display.

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: From `development` branch

**Other Installed Mods**
- None

**Additional info**
![image](https://user-images.githubusercontent.com/20463031/93002610-e7916900-f540-11ea-8ca1-d94f4a09eef5.png)

**Comment by ILikePlayingGames** [comment]
Thanks! I'm working on it

**Comment by iHDeveloper** [comment]
I tested the fix **(2be96ca)** and the issue is solved now.
Thank you @ILikePlayingGames
