### ISSUE TITLE
[Bug] <Potion effect sidebar time left>

### ISSUE THREAD

**Issue by DeltaTempest** [BiscuitDevelopment/SkyblockAddons#398]
**Before that, i want to say sorry about the title, idk what "potion effect sidebar timeleft" feature name**

So, first of all this is my first time i install this Skyblock Addons mod, i haven't install it before so i didn't now if this feature still existed on this version or not, and i didn't know it's a bug, or it's something wrong to my computer. But i have seen people making thread of it on hypixel forums so i posted this

When i drink or use an potion, in can't see potion effect time left on my sidebar, it didn't show anything.
I only can see it on Tab view. I thinks it's strange cause i see the biscuit video. And it's show the "potion effect time left" feature

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.5.2

**Other Installed Mods**
- Patcher mod
- Scrollable tooltips
- Optifine

If this feature is really bug, i hope in the future update this feature will be fix soon

**Thanks For Attention**

**Comment by ILikePlayingGames** [comment]
Hi, thanks for your bug report! This feature was broken because Hypixel changed how potions are displayed in their latest Skyblock update. It will be fixed very soon.

**Comment by ILikePlayingGames** [comment]
Fixed in 1.5.3
