### ISSUE TITLE
[Bug] Bait Counter does not show bait in Fishing Bag

### ISSUE THREAD

**Issue by B-JHu** [BiscuitDevelopment/SkyblockAddons#410]
**Describe the bug**
The bait counter does not show the bait and the number of baits, when those baits are in the fishing bag. 

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Have baits in inventory
2. Switch to a fishing rod
3. Have baits show as intended
4. Put baits in fishing bag
5. Switch to a fishing rod once more 
6. See that the baits do not get shown at all 
(I used the Prismarine Rod if that is of any significance)

**Expected behavior**
The "module" should show the baits, regardless of whether the bait is in the inventory directly or the fishing bag.

**System Information**
 - OS: Windows 7 Pro, Service Pack 1 Build 7601
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.5.3

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- BazaarNotifier 1.3.0
- Schematica 1.7.7.143 (w/ the associated Lunatrius-Core 1.1.2.32)
- Optifine HD_U_I3
- 5zig Mod v3.11.1

**Additional info**
Not a "game breaker", just a small inconvenience, but a bug nonetheless.

**Comment by MenTwo** [comment]
B-JHu,

While this isn't an intended feature, it's a known issue. When Biscuit had been making the bait counter, he had encountered issues with how often the Fishing Bag would update for the player's API, where it wouldn't be near as accurate as the counter in the inventory. Because of this, he purposely left out the fishing bag Bait Tracker.

**Comment by Charzard4261** [comment]
TFW Biscuit gets Bait Tracker cred D:

**Comment by C13H10** [comment]
honestly only good way to do bait tracker is to open bait bag and then just check the bait gui for bait
