### ISSUE TITLE
[Bug] Selecting Menu Options from Housing Menu Item Crashes the Game

### ISSUE THREAD

**Issue by DedicatedMedic** [BiscuitDevelopment/SkyblockAddons#415]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
Attempting to use the menu from the Housing Menu Item in Hypixel will crash the game with the message:
The game crashed whilst updating screen events
Error: java.lang.NullPointerException: Updating screen events
Exit Code: -1

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Go to your player home in housing
2. Activate the menu item from your inventory
3. Attempt to use a menu item ex: Weather
4. Crash to launcher

**Expected behavior**
The next menu should open.

**Crash Report**
[crash-2020-09-23_15.23.29-client.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/5278508/crash-2020-09-23_15.23.29-client.txt)
[crash-2020-09-23_15.24.26-client.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/5278509/crash-2020-09-23_15.24.26-client.txt)
[crash-2020-09-23_15.28.28-client.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/5278510/crash-2020-09-23_15.28.28-client.txt)
[crash-2020-09-23_15.31.40-client.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/5278511/crash-2020-09-23_15.31.40-client.txt)
[crash-2020-09-23_15.36.19-client.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/5278512/crash-2020-09-23_15.36.19-client.txt)
[crash-2020-09-23_15.37.07-client.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/5278513/crash-2020-09-23_15.37.07-client.txt)
[crash-2020-09-23_16.32.27-client.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/5278514/crash-2020-09-23_16.32.27-client.txt)
[crash-2020-09-24_14.39.47-client.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/5278515/crash-2020-09-24_14.39.47-client.txt)

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - SkyblockAddons Version: [e.g. 1.5.2]

**Other Installed Mods**
I normally run Optifine/JEI/NEU/Patcher but I removed them to test so I was only running SBA on the last crash.
Forge - 1.15.1.2318 for 1.8.9

**Additional info**

**Comment by ILikePlayingGames** [comment]
Hi, we fixed this in 1.5.4. Please update.
