### ISSUE TITLE
locking slots when not intended

### ISSUE THREAD

**Issue by HamondEggs** [BiscuitDevelopment/SkyblockAddons#418]
i use SBA on BLC and im getting bugs where inventory slots are getting locked that i had previously locked sessions before. every time i start up mc i need to unlock these slots and lock others. its just not saving my last setup, instead its loading an older setup.

**Comment by Debuggingss** [comment]
Hello! SkyblockAddons on the Badlion Client is not made by Biscuit, it is made by the Badlion team. Go to the Badlion forums instead.

**Comment by ILikePlayingGames** [comment]
Debuggingss is right. We don’t maintain their version.
