### ISSUE TITLE
[Bug] Health bar not visible despite enabled

### ISSUE THREAD

**Issue by RobotHanzo** [BiscuitDevelopment/SkyblockAddons#431]
**Describe the bug**
As per the title, health bar doesn't show despite it being enabled in latest version compiled directly from `development` branch

**To Reproduce**
1. Enable health bar
2. Ensure you move it to a visible location
3. Observe

**Expected behavior**
Health bar to directly show

**Screenshots**
![https://cdn.robothanzo.dev/javaw_9VpZ6oE9IM.png](https://cdn.robothanzo.dev/javaw_9VpZ6oE9IM.png)

**System Information**
 - OS: Windows 10 Insider Preview Dev
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: Latest compiled from `development` branch (shows as 1.6.0-b6)

**Other Installed Mods**
Refraction mod pack without LabyMod

**Comment by Badbird-5907** [comment]
can confirm
mods:
Auto GG
LabyMod
Hypixel Auto Complete
Keystrokes
NEU
Optifine
Scrollable Tooltips
Skypixel
TNT Time

**Comment by Phoube** [comment]
This should be addressed in version 1.6.0. Sorry for the delay in closing this, but we appreciate the bug report. Feel free to re-open if the problem persists!
