### ISSUE TITLE
[Bug] Cooldown on reforged Treecapitator/Jungle Axe isn't showing up

### ISSUE THREAD

**Issue by FacioZMafii** [BiscuitDevelopment/SkyblockAddons#438]
**Describe the bug**
When you have a reforged Treecapitator/Jungle Axe to Moil or Toil cooldown isn't showing up (it breaks the Block Treecapitator/Jungle Axe On Cooldown thing too)

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Reforge Treecapitator/Jungle Axe to Moil/Toil 
2. Break a log 
3. Check hotbar 

**Expected behavior**
Cooldown doesn't show up

**Screenshots**
Not a screenshot but still useful
https://youtu.be/P6Q8ctPtlzE

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - SkyblockAddons Version: [e.g. 1.5.4]

**Other Installed Mods**
- NotEnoughUpdates 1.4.5-BETA

**Additional info**
I described only the mods that might collide with sba 
If you need more info just tell me what do you need to know

**Comment by RobotHanzo** [comment]
System Information hasn't been provided, thus I'm using SBA latest compiled (beta6) to test,
![https://cdn.robothanzo.dev/javaw_vdt4ssQ9Ze.png](https://cdn.robothanzo.dev/javaw_vdt4ssQ9Ze.png)
Bug can not be reproduced, have you tried acctually checking if the setting of that feature is enabled

**Comment by RobotHanzo** [comment]
I've PRed a fix for this, if you want to try it out and see if it fixes it, go to #439 and head to Try It Out section and click on the link to download the .zip which contains the .jar for latest beta version with the patch
@FacioZMafii

**Comment by FacioZMafii** [comment]
Ok so imma close this issue and download the file.
And tysm ofc!
