### ISSUE TITLE
[Bug] Treecapitator/Jungle axe cooldown not showing up

### ISSUE THREAD

**Issue by slendyduck** [BiscuitDevelopment/SkyblockAddons#442]
**Describe the bug**
After adding one of the new reforge stones, specifically the "moil log", the cooldown durability bar that normally appeared at the bottom of the treecapitator disappeared and stopped working. To verify if this was the issue I got some jungle axes and noticed that the ones with the "moil" reforge did not have a cooldown, and the ones without the "moil" reforge did have the cooldown.

**To Reproduce**
1. Go to the smithmonger and purchase the "Moil Log"
2. Click on the reforge anvil and apply the "Moil Log" to either a Jungle Axe or Treecapitator
3. If you attempt to break any trees it will work, but the cooldown at the bottom of the item will no longer appear

**Expected behavior**
I expected the cooldown on the axe to still show.

**Screenshots**
[https://imgur.com/jkuZtMS](url)

**Crash Report**
My game did not crash.

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.2318
 - SkyblockAddons Version: 1.5.4

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Optifine HD U L5 (1.8.9)
- Scrollable Tooltips 1.2 (1.8.9)
- LLOverlayReloaded 1.0.5-mc (1.8.9)
- Fullbright 1.2.1 (1.8.9)

**Additional info**

**Comment by RobotHanzo** [comment]
This issue is already k own, a fix is avaliable at  [https://github.com/BiscuitDevelopment/SkyblockAddons/pull/439](https://github.com/BiscuitDevelopment/SkyblockAddons/pull/439)
You can download from the Try It Out section to try if it works for you

**Comment by slendyduck** [comment]
Thanks
