### ISSUE TITLE
[Feature Request] Brood Mother Spawn indicator

### ISSUE THREAD

**Issue by Leoguy77** [BiscuitDevelopment/SkyblockAddons#45]
An indicator like Magma Boss Warning just for the Brood Mother

**Comment by ViralTaco** [comment]
Hi. I've never seen a brood mother spawn… Is there a notification in chat when it happens?

**Comment by biscuut** [comment]
theres no notification iirc, im pretty sure it just spawns. the loot is pretty terrible though xd

**Comment by Leoguy77** [comment]
sorry for late answer. no i dont think there is a chat message. also i wouldnt call an uncommon talisman terrible. many poeple need it for their talisman collection

**Comment by ViralTaco** [comment]
Ok, I've never seen the boss. Does it have any distinguishing properties? 
Like is it bigger, smaller, different in any way to other spiders? 
I mean we could check for the name but that sounds slow and I'm not sure if it's an unfair advantage at this point. 

The thing about the magma boss is that it has a chat message. 
So adding sound notification isn't really giving information you don't have. (Ignoring timer)
If there is no chat message then the mod would basically let you know something is there even if you can't see it. Sounds pretty cheaty to me :/ 

NB: sorry for bump

**Comment by tomocrafter** [comment]
There is no looks different between normal spider and brood mother, only for name. and it is really hard to get when it spawns next, it spawns each an hour and separated each server in my optinion.

**Comment by ILikePlayingGames** [comment]
Added in #574.
