### ISSUE TITLE
[Bug] Legendary sea creature warning doesn't work while underwater

### ISSUE THREAD

**Issue by ox-i** [BiscuitDevelopment/SkyblockAddons#458]
**Describe the bug**
Legendary sea creature warning doesn't work while underwater

**To Reproduce**
1.Go underwater
2.Catch a legendary sea creature

**Expected behavior**
There is no sound nor the text on screen appears

**System Information**
 - OS: windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: Beta 1.6 6
**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- powns toggle sneak
-dankers skyblock mod
-5zig reborn
-autogg
-keystrokes
-not enough updates
-optifine
-scrollable tooltips

**Additional info**

**Comment by TrashCan69420** [comment]
does this happen with only sba?

**Comment by Phoube** [comment]
Fishing sea creatures/legendary catch should be fixed in 1.6.0! Sorry it took this long to close this issue, but thanks for the report!
