### ISSUE TITLE
Block Treecapacitor on Cooldown

### ISSUE THREAD

**Issue by Kartoffolo** [BiscuitDevelopment/SkyblockAddons#459]
**Describe the bug**
The Block function for Treecapactior while cooldown doesn't work if your Treecapacitor has the 'Toil' reforge.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Use an Toil Treecapacitor and forage

**Expected behavior**
Without Toil reforge I get a cooldown after cutting down a tree and can't cut another until cooldowns up.

**System Information**
 - OS: [Windows 10]
 - Minecraft Version: [1.8.9]
 - Forge Version: [11.15.1.2318]
 - SkyblockAddons Version: [1.5.4]

**Comment by RobotHanzo** [comment]
A pull request has been opened for this 1 month ago, pending merge
https://github.com/BiscuitDevelopment/SkyblockAddons/pull/439

**Comment by ILikePlayingGames** [comment]
The pull request was merged, the changes will be included in 1.6.0.

**Comment by ILikePlayingGames** [comment]
1.6.0 has been released, but unfortunately this feature had to be removed due to changes in Hypixel rules.
