### ISSUE TITLE
throwable valuables

### ISSUE THREAD

**Issue by toaster-god** [BiscuitDevelopment/SkyblockAddons#461]
**Describe the bug**
You can drop some valuable items

**To Reproduce**
you can drop all math hoes, and most likely the axes, I'm too poor to test it though

**Expected behavior**
You can drop very valuable farming tools with one press of the drop button

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.5.2

rip my sugar cane hoe .-.

**Comment by wwsean08** [comment]
I just tried this with my axes and my tier 2 hoes (rare) and it wasn't allowed, maybe yours were still tier 1 (uncommon)? that could explain it, I don't have the money/resources to buy another one to test but just a thought.

**Comment by ILikePlayingGames** [comment]
Can you please tell me the names of the valuable items that can be dropped? Sean is correct. The filter blocks dropping items with a rarity of rare or higher so if your tools are uncommon you will be able to drop them.

**Comment by wwsean08** [comment]
They are outlined here, https://hypixel-skyblock.fandom.com/wiki/Mathematical_Hoe_Blueprint the name doesn't change between rarities it appears.  Here's an example of my sugar cane hoe data dump:

```
{
    id: "minecraft:iron_hoe",
    Count: 1b,
    tag: {
        ench: [],
        Unbreakable: 1b,
        HideFlags: 254,
        display: {
            Lore: ["§7Speed: §a+9 §9(Blessed +9)", "", "§9Harvesting V", "§7Grants a §a62.5% §7chance to", "§7harvest double crops.", "§9Telekinesis I", "§7Block and mob drops go directly", "§7into your inventory.", "§9Turbo-Cane III", "§7Increases double-drop chance", "§7of sugar cane by §a+15%§7.", "", "§7Harvest §a+25% sugar cane", "§7Gain §a+3% §7Farming Exp", "", "§7Counter: §e1,140,701 Sugar Canes", "", "§6Logarithmic Counter", "§7Harvest §a+16% §7sugar cane per", "§7digits on the Counter, minus 4!", "§fCounter bonus: §a+48% §7sugar cane", "", "§7§8Bonus sugar cane percent", "§8increases your Farmhand perk's", "§8chances", "", "§eReach 10M Counter for +1 Rarity!", "", "§6Right-click to view upgrade recipe!", "", "§9Blessed Bonus", "§7Gain §a+3% §7Farming exp.", "§7Increases the chance for double", "§7crops by §a+9%§7.", "", "§9§lRARE HOE"],
            Name: "§9Blessed Turing Sugar Cane Hoe"
        },
        ExtraAttributes: {
            modifier: "blessed",
            mined_crops: 1140701,
            originTag: "THEORETICAL_HOE_CANE_2",
            id: "THEORETICAL_HOE_CANE_2",
            enchantments: {
                harvesting: 5,
                telekinesis: 1,
                turbo_cane: 3
            },
            anvil_uses: 1
        }
    },
    Damage: 0s
}
```

I'm guessing the ID updates based on level since this is a level 2 hoe.  I'll work on opening a PR to prevent dropping tier 1 hoes since I think it's done via https://github.com/BiscuitDevelopment/SkyblockAddons/blob/development/src/main/resources/enchantedItemBlacklist.json (but feel free to let me know if I'm wrong).

**Comment by ILikePlayingGames** [comment]
Thank you Sean for adding the theoretical hoes to the drop protection list. I also added the jungle axe to the list. I will not add the other common and uncommon axes since they are easily obtainable.
