### ISSUE TITLE
[Bug] <Zealot counter does not work with Frozen Scythe>

### ISSUE THREAD

**Issue by TiaTheFairy** [BiscuitDevelopment/SkyblockAddons#465]
Zealot counter does not work if I kill zealot with frozen scythe. The counter number does not increase while the bug also happens on all features related with zealot ( It works when I kill with sword ).

sba version : v1.5.2

**Comment by TiaTheFairy** [comment]
this still exist in v1.5.4

**Comment by HenrythePanda115** [comment]
This has been widely known for many previous releases as well. Unfortunately, with the way Hypixel detects kills from magic weapons, it may not be possible to include an accurate zealot counter to support magic kills. However, support for this may be added in a future release in a manner similar to the explosive bow support for the zealot counter.

**Comment by Thiago4532** [comment]
Yeah, it's not counting when using Dreadlord Sword too.

**Comment by HenrythePanda115** [comment]
> Yeah, it's not counting when using Dreadlord Sword too.

> Unfortunately, with the way Hypixel detects kills from magic weapons, it may not be possible to include an accurate zealot counter to support magic kills. However, support for this may be added in a future release in a manner similar to the explosive bow support for the zealot counter.

🙃
