### ISSUE TITLE
[Bug] Prismapump not placeable when avoid placing enchanted items enabled

### ISSUE THREAD

**Issue by wwsean08** [BiscuitDevelopment/SkyblockAddons#466]
**Describe the bug**
When the setting to prevent placing enchanted items is enabled, you are unable to place the Prismapump item from the farming event.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Make sure that `Avoid Placing Enchanted Items` is enabled.
1. Get a Prismapump from the new farming vendor.
1. Attempt to place it on your item and see it won't place.
1. Disable `Avoid Placing Enchanted Items`.
1. Attempt to place the item again and see that it is placed.

**Expected behavior**
The item should be placed as while it has the enchanted metadata (seen below), it is a block that is designed to be placed to automatically spread water.

**Screenshots**
N/a

**Crash Report**
N/A

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: Current development version (1.5.4 not affected)

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- OptiFine 1.8.9 HD U_L5

**Additional info**
Prismapump item dump:

```
{
    id: "minecraft:prismarine",
    Count: 3b,
    tag: {
        ench: [],
        HideFlags: 254,
        display: {
            Lore: ["§7Pumps water poured next to it.", "", "§9§lRARE"],
            Name: "§9Prismapump"
        },
        ExtraAttributes: {
            id: "PRISMAPUMP"
        }
    },
    Damage: 2s
}
```

**Comment by ILikePlayingGames** [comment]
Thanks for the bug report! This will be fixed in the next release.

**Comment by Phoube** [comment]
Avoid placing enchanted items was removed from SBA in 1.6.0 due to Hypixel's new mod guidelines. See this issue: #517
