### ISSUE TITLE
[Bug] When you have the "avoid using ember rod ability" toggled on, it won't let u use the builders wand main ability 

### ISSUE THREAD

**Issue by TrvptaPvcks** [BiscuitDevelopment/SkyblockAddons#468]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

When I was trying to build my first layer of netherwarts and I wanted to start creating the layer, I couldn't just place the souls sand. So I asked for help and someone told me that the "avoid using ember rod ability" is working it doesn't let the builders wand correctly. 

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Toggle the "avoid using the ember rod ability while on the island" ability on. 
2. Take ur builder's wand and use soul sand. 
3. Try making the beginning of the layer 

**Expected behavior**

It won't let you place the soul sand. 

**Screenshots**
(no screenshot) 

**Crash Report**
(didn't crashed) 
If your game crashed, please paste your crash report here.

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.5.2

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Optifine latest version for Mc 1.8.9

**Additional info**
Nothing to add, I used soul sand when it happened (so try using it if possible).

**Comment by TrashCan69420** [comment]
try using 1.5.4

**Comment by HenrythePanda115** [comment]
This is a known bug as the ember rod has similar nbt data to the builder's wand. Likely, this will be patched in a future release and/or the ember rod feature being removed as ember rods are unobtainable anymore and are not as common as before.

**Comment by ILikePlayingGames** [comment]
The ember rod feature was removed in v1.6.0 so this issue should no longer occur.
