### ISSUE TITLE
[Bug] "Organize Long Enchantment Lists" removes some T4/6/7 enchants from the lore of items.

### ISSUE THREAD

**Issue by MatthewTGM** [BiscuitDevelopment/SkyblockAddons#474]
**Describe the bug**
Some T4/6/7 enchants (such as sharpness, critical, scavenger, etc) are removed from the enchantment list of items when using the feature stated in the title.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Go to the main mod menu
2. Click on enable Organize Long Enchantment Lists
3. Enchantments are removed

**Expected behavior**
Exactly as the feature name states
The organization of enchantment lists

**System Information**
 - OS: Windows 10 Pro
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons 1.6.0-beta7

**Other Installed Mods**
- OptiFine M5 pre2
- ModCore 0.1.47
- Powns Togglesneak 3.0
- DSM (Danker's SkyBlock Mod) 1.8.5-beta4
- Patcher LOCAL(?)
- Sk1er OAM (Old Animations Mod) 1.0

**Comment by Phoube** [comment]
This should be addressed in version 1.6.0. Feel free to open if the problem persists!
