### ISSUE TITLE
[Bug] <Slot locking 'ignores' certain keybinds>

### ISSUE THREAD

**Issue by Alejoairplane** [BiscuitDevelopment/SkyblockAddons#475]
When using keybinds such as Mouse Button 4/5 (yes this are vanilla keybinds I tried them while having forge disabled) you can "ignore" the Lock Slots option

**To Reproduce**

1. Get a mouse with side buttons or simply extra buttons (I personally use the Steel Series Elite 3 if that's useful)
2. Rebind any slot 1-8 to any of the extra buttons
3. Put item in assigned slots ( so if you made button 4 be slot 3 put your sword on the slot 3) and ofc lock that slot
4. Hover over any slot in your inventory other than the main hotbar ones and press the button (in this case press button 4 and then the item you were hovering over will go to slot 3 even if it was locked)

**Expected behavior**
Locked item will move, aka o noes you can drop your 1b sword or something idk I'm poor

**Screenshots**
Huh...

**System Information**
 - OS: W10 home
 - Minecraft Version: 1.8.9 (why is this a question wut)
 - Forge Version: Latest
 - SkyblockAddons Version: 1.5.4

**Other Installed Mods**
I tried doing this with ONLY sba and it still happened

**Additional info**
I dropped my silk edge cuz of this sad times

**Comment by ILikePlayingGames** [comment]
Sorry about your silk edge sword. I'll look into this when I can.

**Comment by ILikePlayingGames** [comment]
Hi again, this issue has been fixed in 1.6.0. It should stay in the locked slot now.
