### ISSUE TITLE
Can't run ./gradlew setupDecompWorkspace

### ISSUE THREAD

**Issue by itsneyoa** [BiscuitDevelopment/SkyblockAddons#481]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
When attempting to run './gradlew setupDecompWorkspace' build fails with exception "Execution failed for task ':fixMcSources'.
> com.cloudbees.diff.PatchException: Cannot find hunk target"

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Git clone/download zip of either master or development branch
2. Open command prompt/terminal and navigate to the directory
3. Run gradlew setupDecompWorkspace

**Expected behavior**
The build to succeed

**Screenshots**

**Crash Report**
If your game crashed, please paste your crash report here.

**System Information**
 - OS: Windows 10 and MacOS Big sur
 - Minecraft Version: n/a
 - Forge Version: n/a
 - SkyblockAddons Version: Master and Development branch
 - JDK version: 15

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- n/a

**Additional info**
[SBA-Compile-Stacktrace.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/5829729/SBA-Compile-Stacktrace.txt)

**Comment by ILikePlayingGames** [comment]
Can you please try again with JDK 8? ForgeGradle is incompatible with JDK versions newer than 8. Run it with `gradlew setupDecompWorkspace -Dorg.gradle.java.home=/JDK_PATH` so it uses the correct JDK. Before running it, also run `gradlew cleanCache`.

**Comment by itsneyoa** [comment]
Thank you! Worked first time :)
