### ISSUE TITLE
[Bug] Some items don't show in personal compactor preview

### ISSUE THREAD

**Issue by ILikePlayingGames** [BiscuitDevelopment/SkyblockAddons#483]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
Certain items such as snow blocks will not show up on the personal compactor preview

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Put items in personal compactor
2. Look at personal compactor preview
3. Certain items will not show up in the preview

**Expected behavior**
All items in the personal compactor should show up in the personal compactor preview.

**Screenshots/Video**
![2021-01-20_01 01 27 (2)](https://user-images.githubusercontent.com/22475143/105134052-cbd43b80-5abb-11eb-8128-97c5002a7d21.png)
![2021-01-20_01 01 32](https://user-images.githubusercontent.com/22475143/105134061-cecf2c00-5abb-11eb-8f62-fc59a9b095ae.png)

**Crash Report**
N/A

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.5.4-1.6-b.7 dev build

**Other Installed Mods**
N/A

**Additional info**
This happens because we're trying to guess the correct Minecraft item based on the Skyblock ID. The Skyblock and Minecraft item IDs are often different so we need to figure out how to get the correct Minecraft ID for all the different Skyblock items that can go into the compactor.

**Comment by ILikePlayingGames** [comment]
It should be fixed now. The fix will be released in v1.6.0. Thanks @Phoube!

**Comment by Phoube** [comment]
Released!
