### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Xbfo** [BiscuitDevelopment/SkyblockAddons#484]

**Comment by Xbfo** [comment]
sorry, it fixed and i dont know how to delete im new to github

**Comment by Dradonhunter11** [comment]
> sorry, it fixed and i dont know how to delete im new to github

How did you fix it, for me SBA stopped working all together

**Comment by F4ture** [comment]
How u fix?

**Comment by ILikePlayingGames** [comment]
Fixed in v1.5.5
