### ISSUE TITLE
[Bug] No addon appears and they are all activated

### ISSUE THREAD

**Issue by Theroler01** [BiscuitDevelopment/SkyblockAddons#486]
![2021-01-22_01 56 43](https://user-images.githubusercontent.com/77822856/105448529-3ec4ea00-5c55-11eb-9cd8-9207415f4f69.png)
![2021-01-22_01 56 32](https://user-images.githubusercontent.com/77822856/105448536-408ead80-5c55-11eb-930d-7ae9ee707395.png)
![2021-01-22_01 56 37](https://user-images.githubusercontent.com/77822856/105448537-41274400-5c55-11eb-8cfd-f70b0f181021.png)

Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
The bug would be that the skyblockaddons does not let me use the addons it has and only one appears that is the one from the dark auctions, I do not get the magma boss alert or anything, I also activate the life and mana bars and nothing does not let me do nothing only comes out of the dark auctions until a few hours ago it was fine when I disconnected for a while that was when it started

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - SkyblockAddons Version: [e.g. 1.5.2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Example Mod 1.0
Cowlection
Chattrigers
NotEnoughtUpdates

**Additional info**

**Comment by F4ture** [comment]
I have this bug too

**Comment by Czukbol** [comment]
I have the same problem

**Comment by Czukbol** [comment]
Maybe hypixel added something that blocks it or it just got bugged beacuse of update or something

**Comment by SakizciAdam** [comment]
Same problem. It was fine yesterday

**Comment by CoolBoyRule** [comment]
Its because hypixal changed there host i think and it dose not recognize it i think

**Comment by SakizciAdam** [comment]
> Its because hypixal changed there host i think and it dose not recognize it i think

After checking Utils#isOnHypixel they probably are not using bungeecord anymore.

**Comment by defaultenn** [comment]
The same problem

**Comment by NeoNC72** [comment]
https://github.com/BiscuitDevelopment/SkyblockAddons/pull/487

**Comment by SakizciAdam** [comment]
> #487 ez fix

yes I am working on it

**Comment by fallon146** [comment]
i have the same problem too

**Comment by mynamejeff124** [comment]
Same here, hope they fix as it is a very cool mod.

**Comment by ILikePlayingGames** [comment]
Fixed in v1.5.5
