### ISSUE TITLE
[Bug] Mana no longer appears

### ISSUE THREAD

**Issue by Mas9311** [BiscuitDevelopment/SkyblockAddons#491]
**Describe the bug**
Mana bar & Mana pool "current/capacity" numbers do not appear. GUI Location Editor confirms it _should_ be there.

**To Reproduce**
1. Go to any island on any mini server.
1. Look at the location you placed the Mana bar/mana pool numbers.

**Expected behavior**
Mana is suppose to show.

**Screenshots/Video**
Mana expected:
![mana_expected](https://user-images.githubusercontent.com/31224566/105532232-cc312a00-5ca7-11eb-9e26-ab202d277e91.png)
Mana actual:
![mana_actual](https://user-images.githubusercontent.com/31224566/105532253-d521fb80-5ca7-11eb-80b6-88a64de32478.png)

**System Information**
 - OS: Xubuntu 20.04
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.1722
 - SkyblockAddons Version: 1.5.4

**Other Installed Mods**
- Zealot Counter 1.3.0

**Comment by onkel69** [comment]
check #487

**Comment by ILikePlayingGames** [comment]
Fixed in v1.5.5
