### ISSUE TITLE
[Bug] Treecapitator axe cool down not displaying

### ISSUE THREAD

**Issue by TotsIsTots** [BiscuitDevelopment/SkyblockAddons#495]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
In my private island, the cool down bar for my teecapitator axe displays properly, but when I am not in my private island it will not display.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Go somewhere other than your private island
2. Mine a log with a trecapitator axe
3. The cool down will not display

**Expected behavior**
When you mine the log, a cool own bar will not display.

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.5.5

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Optifine 1.8.9
- Xaero's minimap 1.8.9
**Additional info**

**Comment by ILikePlayingGames** [comment]
It's been fixed in the betas and will be included in v1.6.0.
