### ISSUE TITLE
[Bug] Dev branch last commit

### ISSUE THREAD

**Issue by konoashi** [BiscuitDevelopment/SkyblockAddons#499]
After building, when launching this happening:
![image](https://user-images.githubusercontent.com/64316846/106362538-b5cc4380-6323-11eb-8d08-cb034916cc7d.png)
Other mods: Skyblock Extras 2.0.0

**Comment by 116s** [comment]
Duplicate of #467.

**Comment by ILikePlayingGames** [comment]
Closed as duplicate
