### ISSUE TITLE
[Bug] Switching backpacks does not re-color the inventory on the first click

### ISSUE THREAD

**Issue by ILikePlayingGames** [BiscuitDevelopment/SkyblockAddons#506]
This bug was reported by **Endergamer_hun** on Discord.

Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
When a player switches backpacks in their inventory, clicking to open the new backpack does not re-color the inventory UI to the color of the backpack. Clicking the backpack a second time causes the color to appear correctly.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Open player inventory
2. Click on a backpack
3. Click on another backpack
4. Inventory color resets instead of changing to the second backpack's color

**Expected behavior**
The inventory color should change to the new backpack's color when the player switches backpacks instead of resetting to the normal inventory color.

**Screenshots/Video**

https://user-images.githubusercontent.com/22475143/108334388-e32c4480-719f-11eb-9f30-9ff790d870aa.mp4

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.5.5

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.

**Additional info**

**Comment by Phoube** [comment]
Do you know if this still happens in 1.6.0 b9?

**Comment by ILikePlayingGames** [comment]
I can confirm that it does.

https://user-images.githubusercontent.com/22475143/108473712-6317e480-725c-11eb-8997-16712a05f970.mp4

**Comment by ILikePlayingGames** [comment]
the new embed video feature is cool

**Comment by ILikePlayingGames** [comment]
New storage menu makes this obsolete
