### ISSUE TITLE
backpack lock preview not working

### ISSUE THREAD

**Issue by Celexux** [BiscuitDevelopment/SkyblockAddons#508]
**Describe the bug**
Whenever someone trades you a backpack you can't lock the preview of the backpack. It's pretty annoying.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. someone trades you a backpack (eg. you're trying to buy a math hoe)
2. you try to press f/j/ whatever key you've put the hotkey on
3. the backpack preview doesn't lock

**Expected behavior**
The backpack locks like it does in the inventory

**Screenshots/Video**
not really sure how to do this

**Crash Report**
none

**System Information**
 - OS: windows 10 
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.5.5 (should be newest version via github)

**Other Installed Mods**

- NEU 2.0 PRE 24.3
- DSM 1.8.5
- Skytils 0.0.8 pre4 
- Perspective Mod 3.0
- Cowlection 0.12.0
- Pown's toggle sprint 3.0
- Sk1er's scrollable tooltips 1.3
- ScamProtect 1.2.6
- ChatTriggers 1.3.1 (no additional modules installed yet)

**Additional info**
It works 100% in the inventory, only is bugged in trade menus

**Comment by Phoube** [comment]
This should be fixed in version 1.6.0. Feel free to re-open if necessary.
