### ISSUE TITLE
[Question] Question related to avoid breaking stems

### ISSUE THREAD

**Issue by Qwayne** [BiscuitDevelopment/SkyblockAddons#510]
Hello, I would like to know where exactly is the piece of code for avoid breaking stems. I cant seem to find it after the constant browsing of the master zip.

**Comment by ILikePlayingGames** [comment]
It's [here](https://github.com/BiscuitDevelopment/SkyblockAddons/blob/17bcf6383f827d84dac8bd9e8e7f89f594236f99/src/main/java/codes/biscuit/skyblockaddons/asm/hooks/PlayerControllerMPHook.java#L100). Are you having an issue with the feature?

**Comment by Qwayne** [comment]
Oh thanks a lot, and no I didn't have any issues, just wanted to see hows its done so I could replicate it for another block.

**Comment by ILikePlayingGames** [comment]
You're welcome!
