### ISSUE TITLE
invisible items

### ISSUE THREAD

**Issue by AgentKJI** [BiscuitDevelopment/SkyblockAddons#511]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - SkyblockAddons Version: [e.g. 1.5.2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Example Mod 1.0

**Additional info**

**Comment by ILikePlayingGames** [comment]
Can you please complete the bug report form? You have not provided any information other than the title. I can't find the issue based on that alone.

**Comment by ILikePlayingGames** [comment]
I will now close this issue since I haven't received a response from you. Please create a new one with the template filled in if this is still occurring.
