### ISSUE TITLE
[Bug] "Zealot counter does not work with Frozen Scythe"

### ISSUE THREAD

**Issue by RazZer34** [BiscuitDevelopment/SkyblockAddons#518]
Regarding to #465

This is still a bug and even if it can't be fixed by the magic damage thing, it could be counted with the new feature of the **Bestiary**. At least I think it could if not well :p idk

SBA: v1.5.5

**Comment by ILikePlayingGames** [comment]
Thanks for your report! Can you please add your comment to the existing issue instead of creating a new one? I'm closing this one as a duplicate.
