### ISSUE TITLE
[Bug] Backpack Preview displays full backpacks as empty

### ISSUE THREAD

**Issue by ILikePlayingGames** [BiscuitDevelopment/SkyblockAddons#519]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
Backpacks were disabled by Hypixel recently (https://hypixel.net/threads/regarding-disabled-backpacks.4085288/) so the backpack preview displays a bunch of blank slots.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Hover over a backpack
2. Blank slots are shown instead of the backpack's content

**Expected behavior**
The backpack's content should be displayed

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: e.g. 11.15.1.2318
 - SkyblockAddons Version: 1.5.5

**Additional info**
v1.6 has additional checks that mitigate this issue.

**Comment by ILikePlayingGames** [comment]
Hypixel has re-enabled backpacks but NBT data has been removed when the backpack is in any container other than the player's inventory. In the inventory, the NBT data is removed when the player joins a world, but moving the backpack to another slot will restore it.

**Comment by Phoube** [comment]
Should be fixed now in 1.6.0 :D
