### ISSUE TITLE
[Bug] <what's this>

### ISSUE THREAD

**Issue by IKAKUN12345** [BiscuitDevelopment/SkyblockAddons#531]
Language: Japanese
![スクリーンショット 2021-05-20 184839](https://user-images.githubusercontent.com/84504129/118959061-eef4f600-b99c-11eb-8d0e-8ca98f75c576.png)

**Comment by PumpkinXD** [comment]
proper translation for this feature is:
![图片](https://user-images.githubusercontent.com/54535387/121796118-52471080-cc49-11eb-8b17-2002374f0ea9.png)

biscuit prob build this beta before translators translate this feature

**Comment by ILikePlayingGames** [comment]
Can you please try with the 1.6.0 release and see if the issue still happens?

**Comment by Phoube** [comment]
Closing, because this should be fixed with updated translations in 1.6.0.
