### ISSUE TITLE
Dwarven mines random crashing

### ISSUE THREAD

**Issue by Awstheepic** [BiscuitDevelopment/SkyblockAddons#534]
there are some places in the dwarven mines that when I go to them, the game automatically crashes, here's the crash report.

https://paste.ubuntu.com/p/Zfjv6GfZvf/

**Comment by jani270** [comment]
> there are some places in the dwarven mines that when I go to them, the game automatically crashes, here's the crash report.
> 
> https://paste.ubuntu.com/p/Zfjv6GfZvf/

This Issue is caused by Optifine + your texture pack. To fix this use another pack or try to change your connected textures setting:
ESC > options > video  settings > quality and set connected textures to fast or off
