### ISSUE TITLE
Skill update not working

### ISSUE THREAD

**Issue by EsotericDamian** [BiscuitDevelopment/SkyblockAddons#536]
Hypixel changed the action bar to show skills as a percentage instead of actual xp, the skill update gui does not currently work.

**Comment by KetchupxD** [comment]
yes

**Comment by ILikePlayingGames** [comment]
Thank you for your report! We're aware and working on fixing it.

**Comment by ILikePlayingGames** [comment]
This issue has been fixed in 1.6.0.
