### ISSUE TITLE
the skill xp bar wont change and stays on percentage

### ISSUE THREAD

**Issue by rednaxelaMC** [BiscuitDevelopment/SkyblockAddons#539]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - SkyblockAddons Version: [e.g. 1.5.2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Example Mod 1.0

**Additional info**

**Comment by NottCurious** [comment]
this is not the problem of the mod, Hypixel themselves removed the skill exp tracking feature and replaced it with a percentage.

**Comment by Phoube** [comment]
Hi @rednaxelaMC, please note that we have just released version 1.6.0 (see https://github.com/BiscuitDevelopment/SkyblockAddons/releases/tag/v1.6.0 for the download). I'm closing this for now, but if the problem persists, please open another issue and we will have another look.
