### ISSUE TITLE
[Bug] Cant mine stone in the deep caverns

### ISSUE THREAD

**Issue by BigBrainer1** [BiscuitDevelopment/SkyblockAddons#544]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
This was previously a feature, but it was later removed. Still though, I cant mine stone.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Go to skyblock deep caverns
2.  try to mine stone
3. cant

**Expected behavior**
I expected to break the stone

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - SkyblockAddons Version: [e.g. 1.5.2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Example Mod 1.0

**Additional info**

**Comment by ILikePlayingGames** [comment]
Hi, can you please provide more details? What forge version are you using, what sba version are you using, and do you have any other mods?

**Comment by Phoube** [comment]
Hi @BigBrainer1, please note that we have just released version 1.6.0 (see https://github.com/BiscuitDevelopment/SkyblockAddons/releases/tag/v1.6.0 for the download). I'm closing this for now, but if the problem persists, please open another issue and we will have another look.
