### ISSUE TITLE
Unable to disable enchantment chroma

### ISSUE THREAD

**Issue by CoderBoyo** [BiscuitDevelopment/SkyblockAddons#547]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
I can't disable the enchantment chroma

**To Reproduce**
I updated to the newest mod version.

**Expected behavior**
I want to be able to turn it off

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.6.0

**Other Installed Mods**
I'm sorry it would take to long to list and the issue only occured when i updated the mod to the latest release.

**Comment by Phoube** [comment]
Do `/sba` -> "Parse Enchant Tooltips" -> Click the arrow for the 2nd page -> Modify the enchant tier colors, or turn it off entirely by toggling "Highlight Special Enchantments"

**Comment by Phoube** [comment]
Going to close for now. Feel free to open this back up if you still feel that there's a problem.
