### ISSUE TITLE
[Bug] Nopo: "You didn't fix the commas"

### ISSUE THREAD

**Issue by Phoube** [BiscuitDevelopment/SkyblockAddons#549]
Compatibility with comma coloring in "Parse Enchant Tooltips" is broken. Even with "Highlight Special Enchantments" turned off, the commas are colored with SBA.

![](https://cdn.discordapp.com/attachments/472840295097303040/863298202840858634/unknown.png)

![](https://cdn.discordapp.com/attachments/472840295097303040/863298228028178432/unknown.png)
(See how the green commas still appear in the tooltip)

**Comment by ILikePlayingGames** [comment]
Nopo fixed the commas
