### ISSUE TITLE
[Bug] New release shipped with a potencial unworking/unallowed feature

### ISSUE THREAD

**Issue by raikoh0** [BiscuitDevelopment/SkyblockAddons#550]
Axe Cooldown Indicator appears not to be working? can someone confirm this?

Copied from https://github.com/BiscuitDevelopment/SkyblockAddons/issues/314

Describe the bug

Sba blocks my axe for a shorter amount of time than my actual cooldown. That triggers an "unblock", allowing me to cut 1 wood. When I do so, the ability didn't work because the cooldown wasn't actually finished. However, SBA blocks me from cutting another wood since it thinks that I'm in a new cooldown.

To Reproduce
Steps to reproduce the behavior (how did you get this bug to occur):

    Cut a wood
    Spam left-click to try to cut a new one
    Eventually SBA will let you do it, but that'll happen before your cooldown runs out
    See error; you can't cut the wood for 2 whole seconds even if you can use your ability.

Expected behavior
SBA is supposed to block your axe for the whole cooldown and not just the first ~1.5seconds.
Perhaps add 0.3s more or less to make sure sba lets you hit AFTER the cooldown finished.

Screenshots

Crash Report
If your game crashed, please paste the beginning of your crash report here. Copy from the beginning until the line shown below.

    A detailed walkthrough of the error, its code path and all known details is as follows:

System Information

    e.g. Windows 10
    Mod Loader: Forge
    Minecraft Version: 1.8.9
    SkyblockAddons Version Latest (1.6)

**Comment by Phoube** [comment]
Hi @raikoh0, the new version of SBA does not include blocking your right click during the cooldown. This is because, due to the updated mod guidelines, it's most likely a bannable modification. The feature currently shows if the axe is on cooldown using the durability of the axe in your hotbar. It doesn't actually block your clicks.

**Comment by Phoube** [comment]
Closing cause I think I cleared up the confusion and at the moment there's nothing I can do to re-enable the feature.
