### ISSUE TITLE
Change the name for "Disable Empty Glass Panes" to include the word tooltip or something

### ISSUE THREAD

**Issue by Ownwn** [BiscuitDevelopment/SkyblockAddons#552]
I spent like 10 mins looking for the setting to turn off SBA's feature of hiding your tooltips when you hover over a glass pane and I finally found it. the name is really dumb, it needs to include the word "tooltip" to make searching for it easier

**Comment by Phoube** [comment]
@ImRodry Any thoughts?

**Comment by ImRodry** [comment]
Well this is a tricky one because the current one is indeed misleading but it’s hard to come up with a better name for it. I’ll think of something better when I’m home and I’ll send it here for you to give me your feedback.

**Comment by ImRodry** [comment]
Hey! We're thinking of changing it to `Hide Menu Glass Pane Tooltips`. Would this be clear enough?

**Comment by Ownwn** [comment]
Yes that sounds good!
