### ISSUE TITLE
[Bug] Glow feature doesn't work with Optifine M5

### ISSUE THREAD

**Issue by karmette** [BiscuitDevelopment/SkyblockAddons#555]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
The "glow items" feature doesn't work with Optifine M5 (latest version)

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. use Optifine M5 and SBA 1.6
2. Drop any item
3. no glow :(

**Expected behavior**
item is supposed to glow.

**Screenshots/Video**
takes 5 seconds to reproduce

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: windows 7
 - Minecraft Version: 1.8.9
 - Forge Version: forge1.8.9-11.15.1.2318-1.8.9
 - SkyblockAddons Version: SkyblockAddons-1.6.0-for-MC-1.8.9

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- when testing, only Optifine M5 and skyblock addons 1.6.0 is used.

**Additional info**
used to work, for some reason broke out of no where...

**Comment by Phoube** [comment]
Please make sure Fast Render, Shaders, and Anti aliasing are turned off in your minecraft settings

**Comment by ILikePlayingGames** [comment]
Closed, stale
