### ISSUE TITLE
[Bug] Sba Causes massive error logs

### ISSUE THREAD

**Issue by notahumanthatisimportant** [BiscuitDevelopment/SkyblockAddons#557]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
at some point during gameplay there is a massive error that takes like 99k lines

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Go to 'hypixel.net'
2. Click on 'play for a while'
3. look at logs

**Expected behavior**
no error

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
Attaching error, warning: normal txt file is 9 MB

**System Information**
 - OS: 
[MultiMC_log.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/6835537/MultiMC_log.txt)
Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.6.0

**Additional info**

**Comment by notahumanthatisimportant** [comment]
[MultiMC_log.zip](https://github.com/BiscuitDevelopment/SkyblockAddons/files/6835540/MultiMC_log.zip)

**Comment by uwuplant** [comment]
All of those errors are related to the Danker's skill tracker from what I can tell.

**Comment by notahumanthatisimportant** [comment]
that is untrue because i removed dankers mod

**Comment by notahumanthatisimportant** [comment]
oh srry wrong log
[Multimc_log2.zip](https://github.com/BiscuitDevelopment/SkyblockAddons/files/6835559/Multimc_log2.zip)

**Comment by Phoube** [comment]
This log looks like a vanilla log to me. Though it's long and cut off at the end, there's no indication to me that this is an SBA issue.

**Comment by ILikePlayingGames** [comment]
I agree. The scoreboard errors are a Hypixel issue that occurs when playing dungeons. Please contact Hypixel instead.
