### ISSUE TITLE
[Bug] Skill bar not showing due to conflict with DSM

### ISSUE THREAD

**Issue by PCRGaming** [BiscuitDevelopment/SkyblockAddons#565]
When I was farming enderman I realised that the skill bar was not showing up

![image](https://user-images.githubusercontent.com/65746213/130884071-c55ebded-c63b-4c4c-ac02-f74320a8897a.png)
[](url)

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.6.0

**Other Installed Mods**
- Patcher 1.6.1
- Neu 1.7REL
- Essential
- Dungeons Rooms Mod 3.2.0
- Scrollable Tooltips 1.4
- Dankers Skyblock Mod 1.8.6

**Comment by TheUnrealOculus** [comment]
Hasn't shown up for me either, maybe NEU or DSM are conflicting because I have those installed as well.

**Comment by PCRGaming** [comment]
Ye I realised it was DSM 2 days ago but i forgot to say

**Comment by ILikePlayingGames** [comment]
Fixed in DSM 1.8.7 beta 5
