### ISSUE TITLE
[Game Crash] <Unexpected Error>

### ISSUE THREAD

**Issue by MarkusWilliamsDev** [BiscuitDevelopment/SkyblockAddons#568]
[crash-2021-09-09_00.19.04-client copy.txt](https://github.com/BiscuitDevelopment/SkyblockAddons/files/7133366/crash-2021-09-09_00.19.04-client.copy.txt)
Attached is a crash report from what I think was a crash casued by SBA. 
For more context, I was standing in the dungeon hub for a minute or two (not in party or queued for anything) and just crashed. P.S. Thanks for all of the work you do to make a great mod for so many users :)

**Comment by ILikePlayingGames** [comment]
Fixed in an essential update on Dec. 20, 2021
