### ISSUE TITLE
Discord rich presence has the wrong account.

### ISSUE THREAD

**Issue by Jforjo** [BiscuitDevelopment/SkyblockAddons#569]
Not sure if this is a bug or not, or if this feature needs to be added. My Discord rich presence works, but on the wrong account (I have 2 discord accounts). I want there to be a sign-in option, or for SBA to link it to the account linked with Hypixel itself.
Thanks.

**Comment by ILikePlayingGames** [comment]
Hi, sorry for the late reply. The Discord account used is the one you're logged into on the Discord app. Please login to the account you want to use within the discord app.

**Comment by SuperHotWasabi** [comment]
I'm in the discord developer portal, logged into the same account associated with the account I want it on and it still is being applied to my other account. Is there any other reason why this may be happening?
