### ISSUE TITLE
[Bug] Replace Roman number and NEU rename

### ISSUE THREAD

**Issue by syrun97** [BiscuitDevelopment/SkyblockAddons#572]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
*scrambled*Z O O 1000*scrambled* in item name

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. paste &&Z&&kz&&ZZ O O M&&k1 on neurename
2. turn on sba replace roman number
3. ![2021-09-30_22 33 13](https://user-images.githubusercontent.com/19798397/135466044-e4bc96ec-ba1f-4f7b-91e3-1c0093039e6a.png)
4. ![2021-09-30_22 39 27](https://user-images.githubusercontent.com/19798397/135466085-dda9d551-1e5b-4ad8-bab0-3e62e9a6e477.png)

**Expected behavior**
no Z O O 1000 in item name
**Screenshots/Video**
in to reproduce.
**Crash Report**
no crash

```text
[Paste Here]
```

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.6.0

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
NEU 2.0 - PRE30.2
Optifine HD U M5

**Additional info**

**Comment by ILikePlayingGames** [comment]
Fixed, will include in 1.6.2
