### ISSUE TITLE
[Bug] Baits not showing on screen in fishing bag

### ISSUE THREAD

**Issue by TerabyteTB** [BiscuitDevelopment/SkyblockAddons#577]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
I put my ice baits in my fishing bag and bait count disappeared. When I put it back into my inventory, the bait count appeared again

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Get bait
2. Put bait in fishing bag
3. bait count disappears even though the fishing bag is supposed to hold baits

**Expected behavior**
The bait count shows bait in fishing bag too

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.6.1

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Skyblock Catia
- Skytils
- Dungeon Rooms
- Patcher
- Optifine
- Cowlection
- Keystrokes
- Scrollable Tooltips
- Not Enough Updates

**Comment by Theboiboi8** [comment]
As far as I know this is a known and acknowledged bug ever since SBA version 1.5. Biscuit said that he was working on a fix but he does not seem to have fixed this

**Comment by ILikePlayingGames** [comment]
Unfortunately there isn't really a feasible way to implement this. We can't track the number of items in bags/sacks since Hypixel does not make that available unless the bag is open.
