### ISSUE TITLE
[Bug] "New Chroma" is incompatible with patcher "optimized font rendering"

### ISSUE THREAD

**Issue by Theboiboi8** [BiscuitDevelopment/SkyblockAddons#578]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
When enabling the new chroma with optimized font rendering turned on in Patcher's settings the chroma is single color instead of a fading color and custom chroma enchant colors render as white.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Go to the SBA menu (/sba command in chat).
2. Enable any overlay or UI element like the speed overlay (the one that shows how much speed you have)
3. In the options for the overlay under color enable chroma.
4. Notice how if "enable new chroma" is enabled in general settings and "optimized font rendering" is enabled in Patcher's settings, the overlay is a single changing color. This behavior does not occur without "optimized font rendering"

**Expected behavior**
The color of the element should be a multi-color fading chroma.

**Crash Report**
If your game crashed, please paste your crash report below.

Game does not crash

**System Information**
 - OS: Windows 11
 - Minecraft Version: Forge 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.6.1

**Other Installed Mods**
Many mods but ultimately after testing Sk1er's Patcher is the cause

**Comment by ILikePlayingGames** [comment]
Fixed in #575.
