### ISSUE TITLE
[Bug] Screen turning black

### ISSUE THREAD

**Issue by korny12** [BiscuitDevelopment/SkyblockAddons#585]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
Entire screen turns completely black when looking at glowing items (a option in the mod), when turned off the issue is resolved.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Turn on glowing items
2. Look at a dropped item
3. Have my mod folder (i assume its a confliction)

**Expected behavior**
what? cant rly see yk

**Screenshots/Video**
(https://prnt.sc/246zsnu) i deleted my pickaxe on ironman for this shit cuz 30s despawn timer i cri it is what it is

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: w10
 - Minecraft Version: 189
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.6.1

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- 189 powns togglesneak
- glint colorizer
- minihud
- oldanimationsmod
- patcher
- scrollabletooltips
- sidebarmod
- skyblock extras
- skytils

**Additional info**

**Comment by ILikePlayingGames** [comment]
Hi, thanks for the report! Can you please provide a screenshot of your mod folder? Also, do you have fast render, anti-aliasing, and shaders off in Optifine?

**Comment by wbxshiori** [comment]
Do you use a vanilla resource pack?  I had the same problem when using some resource packs, but I resolved it by deleting unneeded files in the packs.

**Comment by ILikePlayingGames** [comment]
Are you still having this issue?

**Comment by ILikePlayingGames** [comment]
Ok
