### ISSUE TITLE
When I'm without moving for a while, it crashes the game.

### ISSUE THREAD

**Issue by JCCatalann** [BiscuitDevelopment/SkyblockAddons#586]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTJSLoadingPlugin (ctjs-1.3.2-1.8.9.jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.1-for-MC-1.8.9.jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  CrossChatTweaker (CrossChat-1.0 (1.8.9).jar)
  Skytils On Top (Skytils-1.0.9-RC1.jar)
  FMLLoadingPlugin (Compact Chat-1.3 (1.8.9).jar)
  PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  ModTweaker (Patcher-1.7.0 (1.8.9).jar)
  PatcherTweaker (Patcher-1.7.0 (1.8.9).jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 30/11/21 20:18
Description: Failed to read the local localized strings

java.lang.NullPointerException: Failed to read the local localized strings
	at java.util.Objects.requireNonNull(Objects.java:203)
	at codes.biscuit.skyblockaddons.utils.DataUtils.loadLocalizedStrings(DataUtils.java:276)
	at codes.biscuit.skyblockaddons.gui.buttons.ButtonLanguage.func_146112_a(ButtonLanguage.java:55)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:73)
	at codes.biscuit.skyblockaddons.gui.SettingsGui.func_73863_a(SettingsGui.java:162)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1436)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codes.biscuit.skyblockaddons.utils.DataUtils.handleFileReadException(DataUtils.java:398)

-- File being read --
Details:
	File Path: lang/fa_IR.json
Stacktrace:
	at codes.biscuit.skyblockaddons.utils.DataUtils.handleFileReadException(DataUtils.java:398)
	at codes.biscuit.skyblockaddons.utils.DataUtils.loadLocalizedStrings(DataUtils.java:280)
	at codes.biscuit.skyblockaddons.gui.buttons.ButtonLanguage.func_146112_a(ButtonLanguage.java:55)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:73)
	at codes.biscuit.skyblockaddons.gui.SettingsGui.func_73863_a(SettingsGui.java:162)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1436)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Screen render details --
Details:
	Screen name: codes.biscuit.skyblockaddons.gui.SettingsGui
	Mouse location: Scaled: (631, 424). Absolute: (1262, 168)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['XxItsJuancaxX'/2372778, l='MpServer', x=-41,19, y=48,00, z=50,70], EntityOtherPlayerMP['Shruffy'/2372781, l='MpServer', x=-41,22, y=59,06, z=50,69]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 0,00,100,00,0,00 - World: (0,100,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 13000 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 46 total; [EntityArmorStand['Armor Stand'/2372644, l='MpServer', x=-38,50, y=100,00, z=30,50], EntityArmorStand['Armor Stand'/2372645, l='MpServer', x=-26,50, y=100,00, z=30,50], EntityArmorStand['Armor Stand'/2372647, l='MpServer', x=-50,50, y=100,00, z=0,50], EntityArmorStand['Armor Stand'/2372648, l='MpServer', x=-38,50, y=100,00, z=-13,50], EntityArmorStand['Armor Stand'/2372649, l='MpServer', x=-61,50, y=100,00, z=22,50], EntityOtherPlayerMP['08ew9rtwrr'/2372541, l='MpServer', x=13,00, y=100,00, z=-61,00], EntityArmorStand['Armor Stand'/2372619, l='MpServer', x=-74,50, y=100,00, z=4,50], EntityArmorStand['Armor Stand'/2372633, l='MpServer', x=-50,50, y=100,00, z=30,50], EntityArmorStand['Armor Stand'/2372634, l='MpServer', x=-67,50, y=100,00, z=24,50], EntityArmorStand['§e? §aWarp To §cRed'/2403446, l='MpServer', x=0,50, y=99,44, z=10,50], EntityArmorStand['§a? §aWarp To §2PORTALES'/2403447, l='MpServer', x=7,50, y=98,44, z=18,50], EntityArmorStand['Armor Stand'/2372735, l='MpServer', x=-61,50, y=100,00, z=34,50], EntityArmorStand['§d? §aWarp To §6Orange'/2403448, l='MpServer', x=-3,50, y=98,44, z=7,50], EntityArmorStand['Armor Stand'/2372684, l='MpServer', x=-32,50, y=101,00, z=-6,50], EntityArmorStand['Armor Stand'/2372685, l='MpServer', x=-26,50, y=100,00, z=16,50], EntityPlayerSP['XxItsJuancaxX'/2372778, l='MpServer', x=-41,19, y=48,00, z=50,70], EntityArmorStand['Armor Stand'/2372682, l='MpServer', x=-67,50, y=100,00, z=9,50], EntityArmorStand['Armor Stand'/2372683, l='MpServer', x=-62,50, y=100,00, z=-13,50], EntityPainting['Painting'/2372471, l='MpServer', x=7,50, y=102,00, z=-72,97], EntityArmorStand['Armor Stand'/2372698, l='MpServer', x=-72,50, y=100,00, z=-13,50], EntityArmorStand['§8[§7Lv97§8] §6XxItsJuancaxX's Rabbit'/2372780, l='MpServer', x=-41,78, y=49,88, z=50,13], EntityOtherPlayerMP['Shruffy'/2372781, l='MpServer', x=-41,22, y=59,06, z=50,69], EntityOtherPlayerMP['08ew9rtwrr'/2372541, l='MpServer', x=13,00, y=100,00, z=-61,00], EntityArmorStand['Armor Stand'/2372779, l='MpServer', x=-41,84, y=49,13, z=50,72], EntityArmorStand['Armor Stand'/2372736, l='MpServer', x=-50,50, y=100,00, z=16,50], EntityArmorStand['§8? §aWarp To §5Mas Portales'/2409624, l='MpServer', x=8,50, y=98,44, z=32,50], EntityArmorStand['§9? §aWarp To §bIslas de Madera'/2409625, l='MpServer', x=6,50, y=98,44, z=32,50], EntityArmorStand['§6? §aWarp To §dMagenta'/2428099, l='MpServer', x=-24,50, y=99,44, z=6,50], EntityArmorStand['§2? §aWarp To §aCENTRO ISLA'/2409269, l='MpServer', x=7,50, y=98,44, z=31,50], EntityVillager['Villager'/2372446, l='MpServer', x=4,50, y=100,00, z=40,50], EntityOtherPlayerMP['Shruffy'/2372781, l='MpServer', x=-41,22, y=59,06, z=50,69], EntityPainting['Painting'/2372471, l='MpServer', x=7,50, y=102,00, z=-72,97], EntityArmorStand['Armor Stand'/2372540, l='MpServer', x=-50,50, y=100,00, z=-13,50], EntityArmorStand['Armor Stand'/2372542, l='MpServer', x=-62,50, y=100,00, z=0,50], EntityArmorStand['Armor Stand'/2372543, l='MpServer', x=-31,50, y=99,83, z=11,50], EntityArmorStand['Armor Stand'/2372538, l='MpServer', x=-61,50, y=100,00, z=28,50], EntityArmorStand['Armor Stand'/2372539, l='MpServer', x=-67,50, y=100,00, z=29,50], EntityArmorStand['Armor Stand'/2372485, l='MpServer', x=-26,50, y=100,00, z=-13,50], EntityArmorStand['Armor Stand'/2372498, l='MpServer', x=-66,50, y=100,00, z=34,50], EntityArmorStand['§7? §aWarp To §fCasita :3'/2393578, l='MpServer', x=7,50, y=98,44, z=-3,50], EntityArmorStand['§c? §aWarp To §eYellow'/2423794, l='MpServer', x=-79,50, y=16,44, z=80,50], EntityArmorStand['Armor Stand'/2372544, l='MpServer', x=-38,50, y=100,00, z=0,50], EntityArmorStand['Armor Stand'/2372557, l='MpServer', x=-61,50, y=100,00, z=16,50], EntityArmorStand['Armor Stand'/2372558, l='MpServer', x=-72,50, y=100,00, z=-4,50], EntityArmorStand['Armor Stand'/2372572, l='MpServer', x=-26,50, y=100,00, z=0,50], EntityArmorStand['Armor Stand'/2372571, l='MpServer', x=-38,50, y=100,00, z=16,50]]
	Retry entities: 0 total; []
	Server brand: Hypixel BungeeCord (1.0.58) <- vanilla
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	ct.js modules: [Module{name=DeepProxy,folder=.\config\ChatTriggers\modules\DeepProxy,metadata=ModuleMetadata(name=DeepProxy, version=2.0.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Ecolsson, description=null, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=DungeonUtilities,folder=.\config\ChatTriggers\modules\DungeonUtilities,metadata=ModuleMetadata(name=DungeonUtilities, version=0.9.9, entry=loader.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=null, requires=[SettingsManager, PersistentData], helpMessage=null, ignored=null, isRequired=false)}, Module{name=PersistentData,folder=.\config\ChatTriggers\modules\PersistentData,metadata=ModuleMetadata(name=PersistentData, version=1.1.3, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Easily store data that persist between game and ct reloads, requires=[DeepProxy], helpMessage=null, ignored=null, isRequired=false)}, Module{name=SettingsManager,folder=.\config\ChatTriggers\modules\SettingsManager,metadata=ModuleMetadata(name=SettingsManager, version=1.2.2, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Autogenerates a settings file and gui based on the object created and registers. Example usage can be found in UseExample.js, requires=null, helpMessage=null, ignored=null, isRequired=false)}]
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 825142192 bytes (786 MB) / 2181038080 bytes (2080 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 55, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version      | Source                                |
	| ------ | --------------------- | ------------ | ------------------------------------- |
	| UCHIJA | mcp                   | 9.19         | minecraft.jar                         |
	| UCHIJA | FML                   | 8.0.99.99    | forge-1.8.9-11.15.1.2318-1.8.9.jar    |
	| UCHIJA | Forge                 | 11.15.1.2318 | forge-1.8.9-11.15.1.2318-1.8.9.jar    |
	| UCHIJA | PlayerAPI             | 1.0          | minecraft.jar                         |
	| UCHIJA | essential             | 1.0.0        | Essential (forge_1.8.9).jar           |
	| UCHIJA | modcore               | 0.1.51       | Sk1er Modcore-0.1.51 (1.8.9).jar      |
	| UCHIJA | sidebarmod            | 2.0          | [1.8.9] Sidebar Mod Revamp.jar        |
	| UCHIJA | BazaarNotifier        | 1.4.7        | BazaarNotifier-1.4.7.jar              |
	| UCHIJA | compactchat           | 1.3          | Compact Chat-1.3 (1.8.9).jar          |
	| UCHIJA | cross_chat            | 1.0          | CrossChat-1.0 (1.8.9).jar             |
	| UCHIJA | ct.js                 | 1.3.2        | ctjs-1.3.2-1.8.9.jar                  |
	| UCHIJA | dungeonrooms          | 3.2.4        | Dungeon_Rooms-3.2.4.jar               |
	| UCHIJA | hypixel_auto_complete | 1.1.0        | Hypixel Autocomplete-1.1 (1.8.9).jar  |
	| UCHIJA | notenoughupdates      | 2.0.0-REL    | NotEnoughUpdates-2.0.0.jar            |
	| UCHIJA | patcher               | 1.7.0        | Patcher-1.7.0 (1.8.9).jar             |
	| UCHIJA | text_overflow_scroll  | 1.4.0        | Scrollable Tooltips-1.4 (1.8.9).jar   |
	| UCHIJA | skyblockaddons        | 1.6.1        | SkyblockAddons-1.6.1-for-MC-1.8.9.jar |
	| UCHIJA | skyblockcatia         | 1.3.2        | SkyBlockcatia-1.8.9-1.3.2.jar         |
	| UCHIJA | skytils               | 1.0.9-RC1    | Skytils-1.0.9-RC1.jar                 |
	| UCHIJA | ToggleSneak           | 3.2.2        | ToggleSneak-(1.8.9)-v3.2.2.jar        |

	Loaded coremods (and transformers): 
CTJSLoadingPlugin (ctjs-1.3.2-1.8.9.jar)
  com.chattriggers.ctjs.launch.plugin.CTJSTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.1-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  club.sk1er.mods.scrollabletooltips.forge.ClassTransformer
CrossChatTweaker (CrossChat-1.0 (1.8.9).jar)
  club.sk1er.crosschat.tweaker.ClassTransformer
Skytils On Top (Skytils-1.0.9-RC1.jar)
  skytils.skytilsmod.asm.SkytilsTransformer
FMLLoadingPlugin (Compact Chat-1.3 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  api.player.forge.PlayerAPITransformer
ModTweaker (Patcher-1.7.0 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
PatcherTweaker (Patcher-1.7.0 (1.8.9).jar)
  club.sk1er.patcher.tweaker.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 472.12' Renderer: 'NVIDIA GeForce GTX 750/PCIe/SSE2'
	Skytils Debug Info: {HasBetterFPS=false, BetterFPS Version=NONE, Disabled Start Checks=false}
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 750/PCIe/SSE2 GL version 4.6.0 NVIDIA 472.12, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Dark_Skyblock_UI.zip, v13_32x_Hypixel_Skyblock_Pack.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 472.12
	OpenGlRenderer: NVIDIA GeForce GTX 750/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by ILikePlayingGames** [comment]
Thanks for the report! We're looking in to this. Did you have the SBA menu open at the time? Also, is this the correct crash report? It appears to be from a month ago.

**Comment by ILikePlayingGames** [comment]
Did you build the version you're using from source? The issue you're facing was fixed in the commit after the v1.6.1 tag. Can you download a new copy from either the release page or the Discord and replace the one you have with that?
