### ISSUE TITLE
[Bug] Some warps not enabled in Fancy Warp Menu

### ISSUE THREAD

**Issue by ThexXTURBOXx** [BiscuitDevelopment/SkyblockAddons#609]
**Describe the bug**
When the Fancy Warp Menu is enabled, some warps do not work properly.
For example, I have the Forge and Crystal Hollows warps unlocked, but they are not enabled (i.e. not clickable).
They do work normally when doing `/warp forge` or `/warp ch`

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Unlock the Forge warp point
1. Go into the Skyblock Menu and click "Fast Travel" (alternatively type `/warp`)
2. Try to click on (e.g.) `Forge`

**Expected behavior**
The waypoint should be clickable, but it is not

**Screenshots/Video**
![grafik](https://user-images.githubusercontent.com/12763829/156526011-a6e9b414-fc00-4e68-84d6-100f38384a55.png)

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.7.0-beta 1

**Other Installed Mods**
- LabyMod 3.9.20
- MoreOverlays 1.3
- NotEnoughUpdates 2.1-Pre3
- Patcher 1.8.0
- OptiFine 1.8.9_HD_U_M6
- Scrollable Tooltips 1.4
- Skytils 1.2.0-pre2

**Additional info**
Most other waypoints work (haven't tested all of them since I haven't unlocked all of them and also I am not MVP+, so I am not able to get all of them :) )

**Comment by ILikePlayingGames** [comment]
Hi, sorry for the late reply. Do those warp items appear in the normal Hypixel warp menu without advanced mode, or do they appear in advanced mode?

**Comment by ThexXTURBOXx** [comment]
Hi, no problem! :)
Sadly, I do not have MVP+ rank, so I can't test the Advanced Mode.
However, they do not show in normal mode. This could be either a feature or a bug (I believe the latter one since you can unlock the warps without problems without having MVP+ rank and use them using the /warp command).
Because of that, a possibility would be to just delegate clicks from e.g. The Forge warp to the /warp command if the warp is not shown in the normal menu

**Comment by ILikePlayingGames** [comment]
Thank you for the additional info! I've implemented your suggestion and released a new beta that includes it.

**Comment by ThexXTURBOXx** [comment]
Tried the new beta out today, but the buttons still seem to be greyed out:
![grafik](https://user-images.githubusercontent.com/12763829/162939131-5c770145-03bc-4dcd-9b71-07c10cd3f15a.png)
