### ISSUE TITLE
[Bug] Zealot counter doesn't register arrow kills

### ISSUE THREAD

**Issue by Bollet69** [BiscuitDevelopment/SkyblockAddons#630]
**Describe the bug**
Whenever i kill a zealot with a bow, like juju. The zealot counter doesn't go up. I'm almost certain it's because it doesn't register arrow kills.

**To Reproduce**
1. Get a bow
2. Shoot a zealot with the bow
3. Watch the zealot counter not go up

**Expected behavior**
I expect the zealot counter to go up, whenever I kill a zealot with a bow.

**Screenshots/Video**
I don't have any videos, sorry.

**Crash Report**
It did not.

**System Information**
 - OS: Windows 11
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: Latest released

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Skytils. Latest
- Not enough updates. Latest
- Optifine. Latest

**Comment by ILikePlayingGames** [comment]
Sorry, detecting bow and spell kills is a very difficult thing to implement due to the limited information Hypixel provides and my time is currently quite limited. I will not be adding this in the foreseeable future.
