### ISSUE TITLE
Fetchur Information showing wrong item for the day

### ISSUE THREAD

**Issue by ob-julian** [BiscuitDevelopment/SkyblockAddons#631]
**Describe the bug**
Yesterday the Item was 3x Rabbit foot
Today its Superboom TNT 
But the Fetchur Information says today that he wants the Rabbit foots

**System Information**
 - OS: [Windows 10]
 - Minecraft Version: [1.8.9]
 - Forge Version: [11.15.1.2318]
 - SkyblockAddons Version: [1.6.1]
 - Timezone: [Central European Summer Time (GMT (+2))]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Danker.s.Skyblock.Mod 1.8.6
- Autotip 3.0.1
- CofISky 1.3.3-Alpha
- NotEnoughUpdates 2.0.0
- OptiFine 1.8.9_HD_U_M5
- Patcher 1.8.1
- Scrollable TooItips 1.4
- Skypixel 0.0.6

**Comment by ILikePlayingGames** [comment]
This is fixed in the latest beta.
