### ISSUE TITLE
[BUG - solution probably included] Health text is gold even when you have no absorption hearts (When you have god potion → basicly all the time)

### ISSUE THREAD

**Issue by monsterman04** [BiscuitDevelopment/SkyblockAddons#645]
![image](https://user-images.githubusercontent.com/79773093/185602205-1dd4b1db-7c45-4f3d-9b02-d929e9c0a73b.png)
(I just have GOD POTION active)

This is code issue ↓here↓. I think it should be resolved if you just add another check if the current health is bigger then max health and has the absorption effect :D

![image](https://user-images.githubusercontent.com/79773093/185600894-bbe8813d-d347-475d-9d29-76568d989a64.png)
(file: listeners/RenderListener.java , line: 687)

**Comment by ILikePlayingGames** [comment]
Thank you! I'll fix that in the next update.

**Comment by ILikePlayingGames** [comment]
Fixed in https://github.com/BiscuitDevelopment/SkyblockAddons/commit/c4c02b0e19e7acf58b5cc96861fe822ad18026d1
