### ISSUE TITLE
[Bug] Health number and EHP number stuck at 100 and 348 respectively

### ISSUE THREAD

**Issue by efails** [BiscuitDevelopment/SkyblockAddons#646]
**Describe the bug**
This bug happens when I turn on the health or EHP number on. The overlay shows 100 for health and 348 for EHP no matter what armor set or pet I am using, even though me health stat is well over 2500.

**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Open Skyblock Addons once logged into Hypixel Skyblock 
2. Click on Health number or EHP number
3. Close out of Skyblock Addons menu

**Expected behavior**
I expected the health to display an accurate representation of my total health.

**Screenshots/Video**
![2022-08-19_10 19 58](https://user-images.githubusercontent.com/111594064/185673708-14a674d4-3a38-437a-a06e-1ce7848fb547.png)

**System Information**
 - OS: [e.g. Windows 11]
 - Minecraft Version: [1.8.9]
 - Forge Version: [11.15.1.2318]
 - SkyblockAddons Version: [1.6.0]

**Other Installed Mods**
NotEnoughUpdates-2.0.0
OptiFine_1.8.9
Patcher-1.6.1
Skytils-1.2.6

**Comment by Icebluewolf** [comment]
I can reproduce, when I logged in it was 100/100. I went to the spiders den and it is now stuck at `20/841`. I have 1580 health. I can not say that this effects EHP as I dont often check this. I would guess this has something to do with the new SB update and how they messed around with new stats.

**Comment by ILikePlayingGames** [comment]
Please update SBA to v1.7.0.
