### ISSUE TITLE
[Bug] <Fetchur Hypixel>

### ISSUE THREAD

**Issue by TheLudz1** [BiscuitDevelopment/SkyblockAddons#661]
**Describe the bug**
The overlay of Fetchur is not good

**Expected behavior**
Fechur say me, he like big TNT but in the overlay it's appared the same item thats yesterday, for me: 3x 
rabbit foot

**Screenshots/Video**
see my overlay and talk

https://media.essential.gg/75897198-ae81-4632-77da-8bd2f197d400

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - SkyblockAddons Version: 1.6.1

**Other Installed Mods**

- dungeonsguide-3.7.8
- NotEnoughUpdates-2.1-blahaj-rc6
- OptiFine_1.8.9_HD_U_M5
- Patcher-1.8.5 (1.8.9)
- Scrollable Tooltips-1.4 (1.8.9)
- Skytils-1.2.6

Thank you and sorry for my english, you know the french is not good ^^

**Comment by ILikePlayingGames** [comment]
Please update to sba v1.7
