### ISSUE TITLE
[Bug] Fishing sound indicator not working

### ISSUE THREAD

**Issue by MankoMeister** [BiscuitDevelopment/SkyblockAddons#664]
The sound seems to not play anymore, whether fishing in lava or water. All in game sounds are on.

Minecraft 1.8.9

**Other Installed Mods**
SBE
Skytils
Patcher

**Comment by ILikePlayingGames** [comment]
Please see NEU (https://github.com/Moulberry/NotEnoughUpdates/releases) for a better fishing indicator.
