### ISSUE TITLE
[Bug] Skytils hub's warp isn't avalable on hypixel skyblock menu

### ISSUE THREAD

**Issue by Bobito3370** [BiscuitDevelopment/SkyblockAddons#688]
### Discord Username

Bobito#1294

### Bug Description

first of all, excuse my bad english bc I'm french...
So, the bug is that whith the skytils warp's interface, I only have my island unlocked, I can't fast travel with this menu to the hub, but I can with the /hub... I for the moment I can't tell you if I can with somewhere else bc I don't have unlocked yet any fast travel scroll. Do you know how to solve this pls ? Bc it is very annoying sometimes ...
![2023-03-16_15 02 47](https://user-images.githubusercontent.com/128058107/225641698-d9c5d56b-e6b8-422d-bc41-c6a9ca53261d.png)

### SBA Version

1.7.2

### Other Installed Mods

NEU 2.1
Optifine 1.8.9 hd u 17
patcher 1.8.6 (1.8.9)
Scrollable tooltips 1.4 (1.8.9)
skyblockAddons 1.5.5 (1.8.9)
Skytils 1.4.3

### Operating System

windows 11

**Comment by PumpkinXD** [comment]
try disable fancy warp menu then reenable it?

**Comment by PumpkinXD** [comment]
> ok I disabled it but idk how to enable it again now ... 

/sba then search "fancy warp menu"
