### ISSUE TITLE
This project appears to be RATTED, if you see this and you are using it PLEASE uninstall it! this is malware and a RAT.

### ISSUE THREAD

**Issue by scribeby** [BiscuitDevelopment/SkyblockAddons#699]
### Bug Description

https://isthisarat.com/score/d78b8b7d8e11bf3dcfa6bc0e11ff5828ae160f5fa67de4bd344cbb7b91cf2fb4

The code appears to have a .dll attached to it, and it has webhooks and is trying to hide itself.
No normal "skyblock addon" should have this behavior.

### SBA Version

1.7.2

### Operating System

Windows 11

**Comment by GrowlingGrizzly** [comment]
Did you actually look through the compiled code? 

The "Might use Discord webhooks" is actually the mod just getting an avatar.
![image](https://github.com/BiscuitDevelopment/SkyblockAddons/assets/52770460/1f84425d-9040-4bd2-9534-0823cd044ec8)
Along with this, SBA will obviously have some discord stuff (not webhooks) as it has rich presence integration. 

The DLL is a library that is used in SBA called junixsocket, which can be found here and does not seem to be malicious. https://github.com/kohlschutter/junixsocket

The "Decoding a string, likely trying to hide something" is just a URI parser. 

The "Excessive exception handling can indicate obfuscation" is checking for duplicate installations, which has multiple possible exceptions.

Some of the method names do appear obfuscated, but you can see the deobfuscated names here on github.

**Comment by ILikePlayingGames** [comment]
@GrowlingGrizzly Thank you for the excellent explanation. To add a few details: Junixsocket is a library that we use for the Discord rich presence feature. Regarding obfuscated method names, Minecraft itself is obfuscated, so the mod will need to reference the obfuscated names of Minecraft's methods outside a development environment.
