### ISSUE TITLE
[Feature Request] Grappling Hook Timer

### ISSUE THREAD

**Issue by 2468-13579** [BiscuitDevelopment/SkyblockAddons#77]
It would be really cool if you could add some sort of timer in the corner which tells you how many seconds are left till you can use your grappling hook again.

**Comment by tomocrafter** [comment]
I agree with that, I would be really great if this feature added! I want to implement this feature but I'm still bad at rendering something with OpenGL

**Comment by biscuut** [comment]
Theres a cooldowns feature now
